import assert from 'node:assert/strict';
import {createCareerWithSeed} from '../dist/core/engine.js';
import {buildRoutineDecision,resolveRoutineChoice} from '../dist/core/decisions.js';
import {ensureLifestyle,stepLifestyle,lifestylePerformancePenalty} from '../dist/core/lifestyle.js';
import {updateBody} from '../dist/core/dna.js';
import {RNG} from '../dist/core/random.js';
const families=['LOAD','SPACE','SERVICE','RIVALRY','PRESSURE','ADAPTATION','PATH','LIFE'];
const fresh=(age=12)=>{const p=createCareerWithSeed('Hábitos',415,'gremio','Porto Alegre','RS').player;Object.assign(p,{age,position:'GK',careerTurn:10,physicalCondition:70,mentalFatigue:20});return p;};
const event=(turn=10)=>({id:`life-${turn}`,kind:'INFO',title:'Partida',body:'Atuação',tags:[],matchFeedback:{category:'U15',started:true,minutes:70,rating:7,goals:0,assists:0}});
const offer=p=>{p.decisionMemory={recent:[],lastOffered:Object.fromEntries(families.filter(f=>f!=='LIFE').map(f=>[f,p.careerTurn]))};return buildRoutineDecision(p,event(p.careerTurn));};
let n=0;const check=(name,fn)=>{fn();n++;console.log('PASS',name);};
check('age appropriate choices and family cooldown without RNG',()=>{
 for(const age of [12,17,18,25]){const p=fresh(age),state=p.rngState,e=offer(p);assert.equal(e.decisionFamily,'LIFE');assert.equal(e.choices.length,3);assert.equal(p.rngState,state);assert.deepEqual(e.choices.map(c=>c.id),age<18?['routine:leisure','routine:food','routine:gaming']:['routine:leisure','routine:pizza-beer','routine:party']);if(age<18)assert.doesNotMatch(JSON.stringify(e),/cerveja|balada|sexual/i);p.careerTurn++;assert.notEqual(buildRoutineDecision(p,event(p.careerTurn)).decisionFamily,'LIFE');}
});
check('food and adult indulgences change real states without DNA attributes or moral',()=>{
 for(const [age,id,kg,happiness,condition] of [[12,'routine:food',.3,7,-4],[18,'routine:pizza-beer',.4,7,-4],[25,'routine:party',.3,9,-9]]){const p=fresh(age),e=offer(p),rng=new RNG(77),r=rng.state,w=p.weightKg,m=p.morale,dna=structuredClone(p.dna),attrs=structuredClone(p.attributes);assert.ok(resolveRoutineChoice(p,e,id,rng));assert.equal(p.lifestyle.happiness,50+happiness);assert.equal(p.lifestyle.excessKg,kg);assert.ok(Math.abs(p.weightKg-w-kg)<1e-8);assert.equal(p.physicalCondition,70+condition);assert.equal(p.morale,m);assert.deepEqual(p.dna,dna);assert.deepEqual(p.attributes,attrs);assert.equal(rng.state,r);assert.match(p.history[0].detail,/felicidade \+/);assert.match(p.history[0].detail,/peso \(kg\) \+0,[34]/);if(id==='routine:party'){assert.equal(p.lifestyle.sleepDebt,2);assert.equal(p.mentalFatigue,26);}}
});
check('balanced leisure helps recovery and happiness without physical cost',()=>{const p=fresh(),e=offer(p),weight=p.weightKg;ensureLifestyle(p).sleepDebt=1;assert.ok(resolveRoutineChoice(p,e,'routine:leisure',new RNG(1)));assert.equal(p.lifestyle.happiness,53);assert.equal(p.physicalCondition,72);assert.equal(p.mentalFatigue,18);assert.equal(p.weightKg,weight);assert.equal(p.lifestyle.sleepDebt,.5);});
check('forged not offered ids, stale adult options and second resolution are mutation free',()=>{
 const p=fresh(),e=offer(p),rng=new RNG(22),before=JSON.stringify(p),state=rng.state;assert.equal(resolveRoutineChoice(p,e,'routine:pizza-beer',rng),false);assert.equal(JSON.stringify(p),before);
 const stale={...e,choices:[{id:'routine:party',label:'Balada'}]};assert.equal(resolveRoutineChoice(p,stale,'routine:party',rng),false);assert.equal(JSON.stringify(p),before);assert.equal(rng.state,state);
 assert.ok(resolveRoutineChoice(p,e,'routine:gaming',rng));const applied=JSON.stringify(p);assert.equal(resolveRoutineChoice(p,e,'routine:gaming',rng),false);assert.equal(JSON.stringify(p),applied);
});
check('recovery idempotence and persistent bounded costs for next two rounds',()=>{const p=fresh(18),e=offer(p);resolveRoutineChoice(p,e,'routine:party',new RNG(1));const first=lifestylePerformancePenalty(p);assert.ok(first>0&&first<=8);p.careerTurn++;stepLifestyle(p);const second=lifestylePerformancePenalty(p),snapshot=JSON.stringify(p);assert.ok(second>0&&second<first);stepLifestyle(p);assert.equal(JSON.stringify(p),snapshot);p.careerTurn++;stepLifestyle(p);assert.ok(lifestylePerformancePenalty(p)>0);assert.ok(p.lifestyle.excessKg>0);p.lifestyle.excessKg=12;p.lifestyle.sleepDebt=8;assert.equal(lifestylePerformancePenalty(p),8);});
check('legacy absence preserves weight, initialization and resting do not erase excess',()=>{const p=fresh(),w=p.weightKg;delete p.lifestyle;stepLifestyle(p);assert.equal(p.weightKg,w);assert.equal(lifestylePerformancePenalty(p),0);ensureLifestyle(p);assert.equal(p.weightKg,w);assert.equal(p.lifestyle.happiness,50);p.lifestyle.excessKg=.3;p.lifestyle.sleepDebt=2;const e={...event(),decisionFamily:'LOAD',choices:[{id:'routine:rest',label:'Descansar'}]};resolveRoutineChoice(p,e,'routine:rest',new RNG(1));assert.equal(p.lifestyle.excessKg,.3);assert.equal(p.lifestyle.sleepDebt,1.25);});
check('youth body maturation preserves separate excess with identical RNG',()=>{const normal=fresh(),loaded=structuredClone(normal);ensureLifestyle(loaded).excessKg=.4;loaded.weightKg+=.4;const a=new RNG(1),b=new RNG(1);updateBody(normal,a);updateBody(loaded,b);assert.ok(Math.abs(loaded.weightKg-normal.weightKg-.4)<1e-8);assert.equal(a.state,b.state);assert.equal(loaded.lifestyle.excessKg,.4);});
check('receipts report clamped real changes',()=>{const p=fresh(18),e=offer(p);Object.assign(ensureLifestyle(p),{happiness:99,excessKg:11.9,sleepDebt:7.5});Object.assign(p,{physicalCondition:2,mentalFatigue:99});resolveRoutineChoice(p,e,'routine:party',new RNG(1));assert.match(p.history[0].detail,/felicidade \+1/);assert.match(p.history[0].detail,/peso \(kg\) \+0,1/);assert.match(p.history[0].detail,/condição −2/);assert.match(p.history[0].detail,/fadiga mental \+1/);assert.match(p.history[0].detail,/carga de sono \+0,5/);});
console.log(`${n} lifestyle groups PASS`);
