import {CLUBS,POSITIONS,createGame,choose,overall,club,validGame} from './engine.mjs';
const protoRoot=document.querySelector('#app');
const protoKey='1903.prototype10.v1';
let protoGame=null,protoPage='play',protoError='',protoRaw=null,protoDelta={};
const protoEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const protoN=(v,dec=0)=>Number.isFinite(v)?Number(v).toLocaleString('pt-BR',{maximumFractionDigits:dec}):'—';
function protoLoad(){try{const raw=localStorage.getItem(protoKey);if(!raw)return;protoRaw=raw;const g=JSON.parse(raw);if(!validGame(g))throw Error('Formato inesperado');protoGame=g;}catch{protoError='Não foi possível ler a carreira deste protótipo. Os dados originais foram preservados.';}}
function protoStore(){try{localStorage.setItem(protoKey,JSON.stringify(protoGame));protoError='';}catch{protoError='O navegador não permitiu salvar. Você pode continuar nesta tela; exporte a carreira para preservá-la.';}}
function protoDownload(value,name,type='application/json'){const u=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function protoShell(content){return `<main class="shell"><header class="topline"><span class="wordmark">1903</span><span class="edition">DEZ CLUBES<br>PROTÓTIPO · 01</span></header>${protoError?`<p class="notice" role="status">${protoEsc(protoError)}</p>`:''}${content}</main>`;}
function protoStart(){protoRoot.innerHTML=protoShell(`<section class="intro"><span class="eyebrow">Um campo. Muitas possibilidades.</span><h1>De desconhecido<br>a jogador desejado.</h1><p class="start-copy">Comece aos 12. Descubra seu futebol, conquiste uma vaga e enfrente três temporadas profissionais. Dez clubes. Seu caminho depende do que você faz em campo.</p></section><form class="panel start-form" id="proto-start"><label>Nome do jogador<input name="name" maxlength="35" placeholder="Seu nome" required autocomplete="off"></label><label>Minha primeira posição<select name="position">${POSITIONS.map(p=>`<option value="${p.id}"${p.id==='ST'?' selected':''}>${protoEsc(p.label)}</option>`).join('')}</select></label><label>Meu clube dos sonhos<select name="dream">${CLUBS.map(c=>`<option value="${c.id}"${c.id==='gremio'?' selected':''}>${protoEsc(c.name)}</option>`).join('')}</select></label><button class="primary" type="submit">Começar minha história</button></form><p class="scope">Recorte rápido, encerrado aos 21 anos. Carreira independente do jogo anterior. Liga e elencos são fictícios; nomes dos clubes dão contexto.</p>${protoRaw&&!protoGame?'<button class="quiet" id="proto-recovery">Baixar os dados preservados</button><button class="quiet" id="proto-new">Começar outra carreira</button>':''}`);document.querySelector('#proto-start')?.addEventListener('submit',e=>{e.preventDefault();if(protoRaw&&!protoGame){protoError='Baixe os dados preservados antes de iniciar outra carreira neste navegador.';protoRender();return;}const f=new FormData(e.currentTarget);protoGame=createGame(String(f.get('name')).trim()||'Jogador',String(f.get('position')));protoGame.dreamClubId=String(f.get('dream'));protoStore();protoRender();});document.querySelector('#proto-recovery')?.addEventListener('click',()=>protoDownload(protoRaw,'1903-prototipo-recuperacao.json'));document.querySelector('#proto-new')?.addEventListener('click',()=>{if(!confirm('Preservar os dados ilegíveis em uma cópia neste navegador e começar outra carreira?'))return;try{localStorage.setItem(protoKey+'.recovery.'+Date.now(),protoRaw);protoRaw=null;protoError='Cópia preservada neste navegador. Você pode criar outra carreira.';protoRender();}catch{protoError='Não foi possível preservar a cópia. Baixe os dados antes de tentar novamente.';protoRender();}});}
function protoStates(){const g=protoGame;const items=[['condition','Físico',false],['fatigue','Fadiga',true],['pressure','Pressão',true],['confidence','Confiança',false],['trust','Treinador',false]];return `<section class="hud" aria-label="Condição do jogador">${items.map(([key,label,inverse])=>{const v=g[key]??50,tone=inverse?(v<=30?'good':v<=60?'warn':'bad'):(v>=70?'good':v>=40?'warn':'bad'),delta=protoDelta[key],d=Number.isFinite(delta)&&Math.abs(delta)>=.1?`${delta>0?'+':''}${protoN(delta,1)}`:'—';return `<div class="state" role="group" aria-label="${label}: ${protoN(v)} de 100; ${inverse?'menor':'maior'} é melhor. Variação ${d}"><span>${label}</span><strong class="${tone}">${protoN(v)}</strong><small>${d}</small></div>`;}).join('')}</section>`;}
const protoSkills={finishing:'Finalização',passing:'Passe',reading:'Leitura',pace:'Velocidade',defending:'Defesa',goalkeeping:'Goleiro'};
function protoSkillRows(){const g=protoGame;return `<section class="panel"><div class="section-label" style="margin-top:0"><span>Habilidades adquiridas</span><span>Escala adulta · 0–99</span></div><div class="skills">${Object.entries(protoSkills).map(([key,label])=>{const val=g.skills[key],ref=g.age<18?g.age<14?25:40:55,tone=val>=ref+8?'good':val<ref-8?'bad':'warn';return `<div class="skill ${tone}" title="${protoEsc(label)}: ${protoN(val,1)}. Referência deste recorte ${ref}; não é potencial."><div class="skill-row"><span>${label}</span><strong>${protoN(val,1)}</strong></div><div class="bar" aria-hidden="true"><i style="width:${Math.min(99,Math.max(0,val))}%"></i></div></div>`;}).join('')}</div></section>`;}
function protoStats(s){if(!s)return '';return `<div class="statline" aria-label="Estatísticas observadas"><div><strong>${protoN(s.apps)}</strong>jogos</div><div><strong>${protoN(s.starts)}</strong>titular</div><div><strong>${protoN(s.minutes)}</strong>minutos</div><div><strong>${protoN(s.goals)}</strong>gols</div><div><strong>${protoN(s.assists)}</strong>assistências</div><div><strong>${s.apps?protoN(s.ratingSum/s.apps,1):'—'}</strong>nota</div></div>`;}
function protoGoal(){const g=protoGame,c=club(g),dream=CLUBS.find(c=>c.id===g.dreamClubId);return `<p class="objective">${g.objective?protoEsc(g.objective):g.age<18?'Primeiro objetivo: descobrir onde seu futebol pode prosperar.':c?`Seu desafio é transformar minutos no ${protoEsc(c.shortName)} em rendimento que abra um projeto maior.`:'Seu desafio é transformar o futebol aprendido em uma oportunidade de contrato.'}${dream?` <strong>Sonho: ${protoEsc(dream.shortName)}.</strong>`:''}</p>`;}
function protoHeader(){const g=protoGame,c=club(g),position=POSITIONS.find(p=>p.id===g.position)?.label??g.position;return `<section class="panel player"><div><span class="eyebrow">${g.age} anos · ${protoEsc(position)}</span><h1>${protoEsc(g.name)}</h1><p>${protoEsc(c?.name??'Formação local')}</p>${g.rival?`<p>Disputa: ${protoEsc(g.rival.name??g.rival)}</p>`:''}</div><div class="overall"><strong>${g.age<16?'—':protoN(overall(g))}</strong><span>Overall</span></div></section>`;}
function protoLastMatches(){const g=protoGame,ms=g.lastMatches??[];if(!ms.length)return '';return `<section class="response"><div class="section-label"><span>O período em campo</span><span>${ms.length} partidas</span></div><div class="matches">${ms.map(m=>`<div class="matchrow"><span>${protoEsc(m.opponent)}</span><span>${m.gf}–${m.ga}</span><small>${m.minutes?`${m.minutes} min · ${m.goals??0} G · ${m.assists??0} A`:'Não entrou'}</small></div>`).join('')}</div>${g.coachReaction?`<p><strong>Treinador</strong> · ${protoEsc(g.coachReaction)}</p>`:''}${g.fanReaction?`<p><strong>Torcida</strong> · ${protoEsc(g.fanReaction)}</p>`:''}</section>`;}
function protoMemories(){const g=protoGame,m=g.fanMemory??{};const array=Object.entries(m).flatMap(([clubId,x])=>[...(x.criticalEntries??[]),...(x.entries??[])].map(text=>`${CLUBS.find(c=>c.id===clubId)?.shortName??clubId} · ${text}`));return array.length?`<details><summary>O futebol lembra · ${array.length} registros</summary><div class="memory-list">${array.slice(-12).map(x=>`<p>${protoEsc(typeof x==='string'?x:x.text??x.description??x.label??'Marco registrado')}</p>`).join('')}</div></details>`:'';}
function protoFooter(){return `<nav class="nav-actions" aria-label="Carreira do protótipo"><button class="quiet" id="proto-history">${protoPage==='history'?'Voltar ao jogo':'Minha história'}</button><button class="quiet" id="proto-export">Exportar carreira</button><button class="quiet" id="proto-reset">Recomeçar</button></nav>`;}
function protoPlay(){const g=protoGame,e=g.event,done=e.kind==='DONE'||g.phase==='DONE';const body=done?`<section class="panel end-card"><span class="eyebrow">O recorte terminou. A carreira ainda pode ir além.</span><h1>${protoEsc(e.title)}</h1><p>${protoEsc(e.body)}</p>${protoStats(g.totalstats)}${protoGoal()}</section>`:`<section class="decision" aria-label="Decisão atual"><span class="eyebrow">${g.age<18?'Formação':`Temporada ${g.season??g.age}`} · ${protoEsc(({FORMATION:'Sua formação',RIVALRY:'Disputa por vaga',PLAN:'Projeto esportivo',DECISIVE:'Jogo importante',INTEREST:'Interesse do mercado',CONTACT:'Negociação',OFFER:'Proposta concreta',DONE:'Sua história'})[e.kind])}</span><h2>${protoEsc(e.title)}</h2><p class="decision-body">${protoEsc(e.body)}</p>${e.choices.map((c,i)=>`<button class="choice" data-proto-choice="${protoEsc(c.id)}" data-proto-event="${protoEsc(e.id)}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${protoEsc(c.label)}</strong>${c.hint?`<small>${protoEsc(c.hint)}</small>`:''}</span><span class="arrow" aria-hidden="true">›</span></button>`).join('')}</section>`;protoRoot.innerHTML=protoShell(`${protoHeader()}${protoStates()}${protoStats(g.seasonStats)}${protoGoal()}${protoSkillRows()}${body}${protoLastMatches()}${protoMemories()}${protoFooter()}`);protoBind();}
function protoHistory(){const g=protoGame;const records=g.history??[];const years=g.yearStats??[];protoRoot.innerHTML=protoShell(`${protoHeader()}<section class="panel"><span class="eyebrow">Seu futebol, até aqui</span>${protoStats(g.totalstats)}${years.map(y=>`<article class="timeline"><h3>${y.age} anos · ${protoEsc(CLUBS.find(c=>c.id===y.clubId)?.shortName??'Clube')}</h3>${protoStats(y)}</article>`).join('')}${records.map(h=>`<article class="timeline"><h3>${protoEsc(h.title??h.club??h.headline??`${h.age??h.season??''} anos · ${CLUBS.find(c=>c.id===h.clubId)?.shortName??'Clube'}`)}</h3><p>${protoEsc(h.body??h.detail??h.text??h.reason??'')}</p>${h.stats?protoStats(h.stats):''}</article>`).join('')}${(g.log??[]).slice(0,20).map(x=>`<p>${protoEsc(typeof x==='string'?x:x.text??x.detail??x.title??'Marco registrado')}</p>`).join('')}</section>${protoMemories()}<details><summary>Os dez clubes deste cenário</summary><div class="league">${CLUBS.map(c=>`<div><span>${protoEsc(c.name)}</span><span>${c.level>=75?'Grande projeto':c.level>=60?'Projeto em crescimento':'Clube de entrada'}</span></div>`).join('')}</div></details>${protoFooter()}`);protoBind();}
function protoBind(){document.querySelectorAll('[data-proto-choice]').forEach(b=>b.addEventListener('click',()=>{if(!protoGame||b.dataset.protoEvent!==protoGame.event.id)return;const before=Object.fromEntries(['condition','fatigue','pressure','confidence','trust'].map(k=>[k,protoGame[k]]));if(!choose(protoGame,b.dataset.protoChoice))return;protoDelta=Object.fromEntries(Object.keys(before).map(k=>[k,protoGame[k]-before[k]]));protoStore();protoRender();document.querySelector('.decision')?.scrollIntoView({block:'nearest',behavior:'instant'});}));document.querySelector('#proto-history')?.addEventListener('click',()=>{protoPage=protoPage==='history'?'play':'history';protoRender();});document.querySelector('#proto-export')?.addEventListener('click',()=>protoDownload(JSON.stringify(protoGame,null,2),'1903-dez-clubes-carreira.json'));document.querySelector('#proto-reset')?.addEventListener('click',()=>{if(!confirm('Recomeçar apenas a carreira deste protótipo? Você pode exportá-la antes.'))return;try{localStorage.removeItem(protoKey);protoGame=null;protoRaw=null;protoDelta={};protoError='';protoPage='play';protoRender();}catch{protoError='Não foi possível apagar a carreira. Ela foi preservada.';protoRender();}});}
function protoRender(){if(!protoGame)protoStart();else if(protoPage==='history')protoHistory();else protoPlay();}
protoLoad();protoRender();
