import assert from 'node:assert/strict';
import {CLUBS,POSITIONS,createGame,choose,overall,club,validGame} from './engine.mjs';
const pick=(g,action)=>g.event.choices.find(c=>c.id.startsWith(`${action}@`));
function policy(g){const e=g.event;if(e.kind==='FORMATION')return pick(g,'formation:technique');if(e.kind==='RIVALRY')return pick(g,'rival:earn');if(e.kind==='PLAN')return pick(g,g.condition<65||g.fatigue>45?'plan:RECOVER':'plan:DEVELOP');if(e.kind==='DECISIVE')return pick(g,'decisive:risk');return e.choices[0];}
function complete(g){let decisions=0;while(g.phase!=='DONE'){assert.ok(validGame(g));const c=policy(g);assert.ok(c);assert.ok(choose(g,c.id));assert.ok(++decisions<=25);}assert.ok(validGame(g));return decisions;}
const sum=matches=>matches.reduce((s,m)=>{if(m.minutes){s.apps++;s.starts+=m.started?1:0;s.minutes+=m.minutes;s.goals+=m.goals;s.assists+=m.assists;s.ratingSum+=m.rating;}return s;},{apps:0,starts:0,minutes:0,goals:0,assists:0,ratingSum:0});
let count=0;const check=(name,fn)=>{fn();count++;console.log('PASS',name);};
let favorable=null,range=[];
check('child learned scale and gradual formation stay below frequent70 at18',()=>{
 const young=[],adult=[];for(let seed=1;seed<=1000;seed++){const g=createGame('Escala','ST',seed);assert.ok(Object.values(g.skills).every(v=>v>=14&&v<=23));young.push(overall(g));for(let i=0;i<3;i++)choose(g,g.event.choices[0].id);adult.push(overall(g));}assert.ok(Math.max(...young)<25);assert.ok(adult.filter(v=>v>=70).length<=10);assert.ok(adult.reduce((a,b)=>a+b)/adult.length>=45);console.log(JSON.stringify({scale1000:{age12:[Math.min(...young),Math.max(...young)],age18:[Math.min(...adult),Math.max(...adult)],age18Mean:adult.reduce((a,b)=>a+b)/adult.length,atLeast70:adult.filter(v=>v>=70).length}}));
});
check('100 seeded careers end at21 /54 actual fixtures /3 preserved years /<=25 decisions across all positions',()=>{
 assert.equal(CLUBS.length,10);assert.equal(POSITIONS.length,8);
 for(let seed=1;seed<=100;seed++){const g=createGame('Teste',POSITIONS[(seed-1)%8].id,seed),d=complete(g);assert.equal(g.age,21);assert.equal(g.playedMatches.length,54);assert.equal(g.yearStats.length,3);assert.equal(g.lastMatches.length,6);assert.deepEqual(g.totalstats,sum(g.playedMatches));for(const s of g.yearStats)assert.deepEqual(Object.fromEntries(Object.keys(g.totalstats).map(k=>[k,s[k]])),sum(g.playedMatches.filter(m=>m.season===s.age)));assert.ok(g.playedMatches.every(m=>m.gf<=m.teamChances&&m.ga<=m.oppChances));assert.ok(g.playedMatches.every(m=>m.minutes===0?m.rating===0&&m.goals===0&&m.assists===0:typeof m.coach==='string'&&typeof m.fans==='string'));assert.ok(g.decisions===d);range.push(d);}
 console.log(JSON.stringify({careers:100,fixtures:5400,decisionsMin:Math.min(...range),decisionsMax:Math.max(...range)}));
});
check('exact current choice / old duplicate / forged / final choices reject without mutations, reload deterministic',()=>{
 const g=createGame('Guarda','ST',17),raw=JSON.stringify(g),id=g.event.choices[0].id;assert.equal(choose(g,'forged'),false);assert.equal(JSON.stringify(g),raw);assert.ok(choose(g,id));const after=JSON.stringify(g);assert.equal(choose(g,id),false);assert.equal(JSON.stringify(g),after);const reload=JSON.parse(after);complete(g);complete(reload);assert.deepEqual(g,reload);const done=JSON.stringify(g);assert.equal(choose(g,id),false);assert.equal(JSON.stringify(g),done);
});
check('favorable seed produces distinct projects, explicit interest/contact/offer and rare decisive follow-through',()=>{
 for(let seed=1;seed<=200;seed++){const g=createGame('Favorável','ST',seed);let markets=[];while(g.phase!=='DONE'){if(g.event.kind==='INTEREST'&&g.market.length>=2)markets.push([...g.market]);choose(g,policy(g).id);}if(markets.length&&g.history.length>=2){favorable={seed,markets,clubs:g.history.map(h=>h.clubId),level:overall(g)};assert.ok(g.playedMatches.filter(m=>m.moment).length===1);assert.ok(g.fanMemory[g.playedMatches.find(m=>m.moment).clubId].criticalEntries.some(text=>text.includes('Momento decisivo')));break;}}
 assert.ok(favorable);assert.notEqual(favorable.markets[0][0],favorable.markets[0][1]);console.log(JSON.stringify({favorable}));
});
check('risk versus safety changes only future fixture with persistent memory; role output coherent',()=>{
 const base=createGame('Momento','ST',favorable.seed);while(base.event.kind!=='DECISIVE')choose(base,policy(base).id);const past=JSON.stringify(base.playedMatches),risk=structuredClone(base),safe=structuredClone(base);choose(risk,pick(risk,'decisive:risk').id);choose(safe,pick(safe,'decisive:safe').id);assert.equal(JSON.stringify(risk.playedMatches),past);assert.equal(JSON.stringify(safe.playedMatches),past);choose(risk,pick(risk,'plan:TEAM').id);choose(safe,pick(safe,'plan:TEAM').id);assert.equal(risk.playedMatches.filter(m=>m.moment).length,1);assert.equal(safe.playedMatches.filter(m=>m.moment).length,1);assert.notDeepEqual({m:risk.lastMatches,trust:risk.trust,pressure:risk.pressure},{m:safe.lastMatches,trust:safe.trust,pressure:safe.pressure});
 const goalkeeper=createGame('Goleiro','GK',8);complete(goalkeeper);assert.ok(goalkeeper.playedMatches.every(m=>m.goals===0));assert.ok(goalkeeper.playedMatches.some(m=>m.saves>0));
});
check('club choice has actual cost / rival memory / offseason totals retained / no RNG-only learned growth',()=>{
 const base=createGame('Clube','ST',favorable.seed);while(base.event.kind!=='OFFER')choose(base,policy(base).id);const move=structuredClone(base),stay=structuredClone(base),old=club(base).id,stats=structuredClone(base.totalstats),archived=structuredClone(base.yearStats);choose(move,move.event.choices[0].id);choose(stay,pick(stay,'market:stay').id);assert.notEqual(club(move).id,old);assert.equal(club(stay).id,old);assert.deepEqual(move.totalstats,stats);assert.deepEqual(move.yearStats,archived);assert.equal(move.trust,45);assert.equal(move.event.kind,'RIVALRY');const partner=structuredClone(move),intrigue=structuredClone(move);choose(partner,pick(partner,'rival:team').id);choose(intrigue,pick(intrigue,'rival:intrigue').id);assert.ok(partner.trust>intrigue.trust);assert.ok(partner.fanMemory[partner.clubId].respect>intrigue.fanMemory[intrigue.clubId].respect);
 const a=createGame('Treino','CM',44),b=structuredClone(a);b.rng=123;for(let i=0;i<3;i++){choose(a,a.event.choices[0].id);choose(b,b.event.choices[0].id);}assert.deepEqual(a.skills,b.skills);assert.equal(overall(a),overall(b));assert.deepEqual(a.dna,b.dna);
});
check('development versus recovery has actual learning/state tradeoff rather than a free permanent best button',()=>{
 const base=createGame('Custo','ST',1);while(base.event.kind!=='PLAN')choose(base,policy(base).id);const recover=structuredClone(base),develop=structuredClone(base);choose(recover,pick(recover,'plan:RECOVER').id);choose(develop,pick(develop,'plan:DEVELOP').id);assert.ok(develop.skills.finishing>recover.skills.finishing);assert.ok(develop.condition<recover.condition);assert.ok(develop.fatigue>recover.fatigue);assert.equal(develop.playedMatches.length,6);assert.equal(recover.playedMatches.length,6);assert.ok(develop.coachReaction.includes('participações'));assert.ok(recover.fanReaction.includes('respeito atual'));
});
check('hydration validates JSON without mutation and rejects broken/nonfinite or invalid enum data',()=>{
 const g=createGame('Validação','CB',5);assert.ok(validGame(g));const before=JSON.stringify(g);assert.ok(validGame(g));assert.equal(JSON.stringify(g),before);for(const mutate of [q=>q.schema=2,q=>q.position='BAD',q=>q.skills.passing=NaN,q=>q.condition=101,q=>q.event.choices[1].id=q.event.choices[0].id,q=>q.clubId='elite-free',q=>q.dna.learning=Infinity]){const q=structuredClone(g);mutate(q);assert.equal(validGame(q),false);}complete(g);assert.ok(validGame(JSON.parse(JSON.stringify(g))));
});
console.log(`prototype10-engine: ${count} groups passed`);
