import {CLUBS,POSITIONS,createGame,choose,overall,club,validGame} from './engine.mjs';
const protoRoot=document.querySelector('#app');
const protoKey='1903.prototype10.v2';
let protoGame=null,protoPage='play',protoError='',protoRaw=null,protoDelta={};
const protoEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const protoN=(v,dec=0)=>Number.isFinite(v)?Number(v).toLocaleString('pt-BR',{maximumFractionDigits:dec}):'—';
function protoLoad(){try{const raw=localStorage.getItem(protoKey);if(!raw)return;protoRaw=raw;const g=JSON.parse(raw);if(!validGame(g))throw Error('Formato inesperado');protoGame=g;}catch{protoError='Não foi possível ler a carreira deste protótipo. Os dados originais foram preservados.';}}
function protoStore(){try{localStorage.setItem(protoKey,JSON.stringify(protoGame));protoError='';}catch{protoError='O navegador não permitiu salvar. Você pode continuar nesta tela; exporte a carreira para preservá-la.';}}
function protoDownload(value,name,type='application/json'){const u=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function protoShell(content){return `<main class="shell"><header class="topline"><span class="wordmark">1903</span><span class="edition">BRASIL · A/B<br>PROTÓTIPO · 04</span></header>${protoError?`<p class="notice" role="status">${protoEsc(protoError)}</p>`:''}${content}</main>`;}
function protoDreamOptions(){return ['A','B'].map(division=>`<optgroup label="Série ${division}">${CLUBS.filter(c=>c.division===division).map(c=>`<option value="${c.id}"${c.id==='gremio'?' selected':''}>${protoEsc(c.name)}</option>`).join('')}</optgroup>`).join('');}
function protoCompetition(g){return g.calendarRevision===1&&g.scheduleDivision?(g.scheduleDivision==='TRANSITION'?'Circuito de transição':`Série ${g.scheduleDivision}`):'Calendário legado';}
function protoClubDirectory(){return `<details><summary>Os clubes do Brasil · 20 na Série A e 20 na Série B</summary>${['A','B'].map(division=>`<h3>Série ${division} · 2026</h3><div class="league">${CLUBS.filter(c=>c.division===division).map(c=>`<div><span>${protoEsc(c.name)} <small>${protoEsc(c.state)}</small></span><span>Nível ${c.level}</span></div>`).join('')}</div>`).join('')}<p class="scope">Divisões de referência: 2026. Níveis e elencos são parâmetros do jogo. Os projetos regionais de saves anteriores continuam disponíveis no histórico.</p></details>`;}
function protoStart(){protoRoot.innerHTML=protoShell(`<section class="intro"><span class="eyebrow">Um campo. Muitas possibilidades.</span><h1>Conquiste espaço.<br>Faça o jogo lembrar.</h1><p class="start-copy">Três etapas de formação. Três temporadas profissionais. Conquiste espaço e seja observado pelos 40 clubes das Séries A e B.</p></section><form class="panel start-form" id="proto-start"><label>Nome do jogador<input name="name" maxlength="35" placeholder="Seu nome" required autocomplete="off"></label><label>Minha primeira posição<select name="position">${POSITIONS.map(p=>`<option value="${p.id}"${p.id==='ST'?' selected':''}>${protoEsc(p.label)}</option>`).join('')}</select></label><label>Meu clube dos sonhos<select name="dream">${protoDreamOptions()}</select></label><button class="primary" type="submit">Começar minha história</button></form><p class="scope">Recorte rápido, encerrado aos 21 anos. Clubes e divisões de 2026; calendário resumido e elencos simulados. Sua carreira deste protótipo continua no mesmo save.</p>${protoRaw&&!protoGame?'<button class="quiet" id="proto-recovery">Baixar os dados preservados</button><button class="quiet" id="proto-new">Começar outra carreira</button>':''}`);document.querySelector('#proto-start')?.addEventListener('submit',e=>{e.preventDefault();if(protoRaw&&!protoGame){protoError='Baixe os dados preservados antes de iniciar outra carreira neste navegador.';protoRender();return;}const f=new FormData(e.currentTarget);protoGame=createGame(String(f.get('name')).trim()||'Jogador',String(f.get('position')));protoGame.dreamClubId=String(f.get('dream'));protoStore();protoRender();});document.querySelector('#proto-recovery')?.addEventListener('click',()=>protoDownload(protoRaw,'1903-prototipo02-recuperacao.json'));document.querySelector('#proto-new')?.addEventListener('click',()=>{if(!confirm('Preservar os dados ilegíveis em uma cópia neste navegador e começar outra carreira?'))return;try{localStorage.setItem(protoKey+'.recovery.'+Date.now(),protoRaw);protoRaw=null;protoError='Cópia preservada neste navegador. Você pode criar outra carreira.';protoRender();}catch{protoError='Não foi possível preservar a cópia. Baixe os dados antes de tentar novamente.';protoRender();}});}
function protoStates(){const g=protoGame;const items=[['condition','Físico',false],['fatigue','Fadiga',true],['pressure','Pressão',true],['confidence','Confiança',false],['trust','Treinador',false]];return `<section class="hud" aria-label="Condição do jogador">${items.map(([key,label,inverse])=>{const v=g[key]??50,tone=inverse?(v<=30?'good':v<=60?'warn':'bad'):(v>=70?'good':v>=40?'warn':'bad'),delta=protoDelta[key],d=Number.isFinite(delta)&&Math.abs(delta)>=.1?`${delta>0?'+':''}${protoN(delta,1)}`:'—';return `<div class="state" role="group" aria-label="${label}: ${protoN(v)} de 100; ${inverse?'menor':'maior'} é melhor. Variação ${d}"><span>${label}</span><strong class="${tone}">${protoN(v)}</strong><small>${d}</small></div>`;}).join('')}</section>`;}
const protoIntentLabels={CREATE:'criar oportunidades',ATTACK:'buscar o gol',CONTROL:'controlar o ritmo',LINK:'conectar o ataque',PRESS:'pressionar',SAFE:'proteger o gol',BUILD:'iniciar a construção',SWEEP:'cobrir a profundidade',HOLD:'proteger o setor',ADVANCE:'avançar',EXTRA:'treino extra',READ:'estudar o jogo',COOPERATE:'trabalhar com o grupo'};
const protoHumanText=v=>String(v??'').replace(/\b(CREATE|ATTACK|CONTROL|LINK|PRESS|SAFE|BUILD|SWEEP|HOLD|ADVANCE|EXTRA|READ|COOPERATE)\b/g,k=>protoIntentLabels[k]);
const protoSkills={finishing:'Finalização',passing:'Passe',reading:'Leitura',pace:'Velocidade',defending:'Defesa',goalkeeping:'Goleiro'};
function protoSkillRows(){const g=protoGame;return `<section class="panel"><div class="section-label" style="margin-top:0"><span>Habilidades adquiridas</span><span>Escala adulta · 0–99</span></div><div class="skills">${Object.entries(protoSkills).map(([key,label])=>{const val=g.skills[key],ref=g.age<18?g.age<14?25:40:55,tone=val>=ref+8?'good':val<ref-8?'bad':'warn';return `<div class="skill ${tone}" title="${protoEsc(label)}: ${protoN(val,1)}. Referência deste recorte ${ref}; não é potencial."><div class="skill-row"><span>${label}</span><strong>${protoN(val,1)}</strong></div><div class="bar" aria-hidden="true"><i style="width:${Math.min(99,Math.max(0,val))}%"></i></div></div>`;}).join('')}</div></section>`;}
function protoStats(s){if(!s)return '';return `<div class="statline" aria-label="Estatísticas observadas"><div><strong>${protoN(s.apps)}</strong>jogos</div><div><strong>${protoN(s.starts)}</strong>titular</div><div><strong>${protoN(s.minutes)}</strong>minutos</div><div><strong>${protoN(s.goals)}</strong>gols</div><div><strong>${protoN(s.assists)}</strong>assistências</div><div><strong>${s.apps?protoN(s.ratingSum/s.apps,1):'—'}</strong>nota</div></div>`;}
function protoGoal(){const g=protoGame,dream=CLUBS.find(c=>c.id===g.dreamClubId);return dream?`<p class="dream">${g.clubId===dream.id?'Você chegou ao clube dos seus sonhos. Agora precisa conquistar seu lugar.':`Seu destino desejado: ${protoEsc(dream.shortName)}.`}</p>`:'';}
function protoObjective(){
 const g=protoGame,o=g.objective;if(!o||typeof o!=='object')return '';
 const archived=o.season&&(o.season!==g.season||o.clubId!==g.clubId);
 const context=archived?`<p class="eyebrow">${o.season} anos · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')} · meta anterior</p>`:'';
 const pendingRole=o.revision===1&&o.status==='ACTIVE',duplicate=o.status!=='ACTIVE'&&g.lastOutcome?.season===o.season&&g.lastOutcome?.clubId===o.clubId;
 const labels={ACTIVE:'Em disputa',MET:'Meta cumprida',MISSED:'Meta não cumprida'};
 const progress=o.progressText??Object.entries(o.progress??{}).filter(([k])=>k!=='current').map(([k,v])=>`${protoN(v)} ${{apps:'jogos',minutes:'min',good:'boas atuações',output:'ações da função'}[k]??k}`).join(' · ');
 const target=pendingRole?`${o.target.apps} participações, ${o.target.minutes} minutos e ${o.target.good} boas atuações. A produção exigida muda com o papel escolhido abaixo.`:o.targetText;
 return `<section class="objective-card" aria-label="Objetivo do treinador">${context}<div class="section-label"><span>${protoEsc(pendingRole?'A prova dos próximos seis jogos':o.title)}</span><span class="${o.status==='MET'?'good':o.status==='MISSED'?'warn':''}">${labels[o.status]??'Em disputa'}</span></div>${o.body&&!duplicate?`<p>${protoEsc(o.body)}</p>`:''}${target?`<p class="target">${protoEsc(target)}</p>`:''}${!duplicate&&!pendingRole?`<p class="objective-progress">${protoEsc(progress)}</p>`:''}</section>`;
}
function protoOutcome(){
 const g=protoGame,o=g.lastOutcome;
 if(!o&&!g.coachReaction&&!g.fanReaction)return '';
 const context=o?.season&&(o.season!==g.season||o.clubId!==g.clubId)?`<p class="eyebrow">${o.season} anos · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')} · resultado anterior</p>`:'';
 return `<section class="outcome">${context}${o?`<h3>${protoEsc(o.title)}</h3><p>${protoEsc(o.body)}</p>`:''}${g.coachReaction?`<p><span class="speaker">Treinador</span> · ${protoEsc(g.coachReaction)}</p>`:''}${g.fanReaction?`<p><span class="speaker">Torcida</span> · ${protoEsc(g.fanReaction)}</p>`:''}</section>`;
}
function protoEvidence(){
 const g=protoGame,r=g.roleEvidence;if(!r||!r.minutes)return '';
 const intent=g.lastMatches?.[0]?.strategy;
 const byIntent={SAFE:['saves','goalsConceded'],SWEEP:['interventions','goalsConceded'],BUILD:['completedPasses','chancesCreated'],HOLD:['interventions','failedInterventions'],ADVANCE:['progressions','chancesCreated'],ATTACK:['shotsOnTarget','goals'],LINK:['chancesCreated','assists'],PRESS:['interventions','progressions'],CREATE:['chancesCreated','keyPasses'],CONTROL:['completedPasses','chancesCreated']};
 const keys=byIntent[intent]??(g.position==='GK'?['saves','interventions']:['CB','FB','DM'].includes(g.position)?['interventions','completedPasses']:['AM','CM'].includes(g.position)?['chancesCreated','completedPasses']:['goals','chancesCreated']);
 const labels={saves:'defesas',goalsConceded:'gols sofridos em campo',interventions:g.position==='GK'?'antecipações':'intervenções',failedInterventions:'intervenções falhas',completedPasses:'passes completos',chancesCreated:'chances criadas',keyPasses:'passes decisivos',goals:'gols',assists:'assistências',shotsOnTarget:'finalizações no alvo',progressions:'progressões'};
 const value=k=>r[k]??g.lastMatches.reduce((sum,m)=>sum+(m[k]??0),0);
 return `<div class="role-evidence" aria-label="Contribuição no período">${keys.map(k=>`<span><strong>${protoN(value(k))}</strong> ${labels[k]}</span>`).join('')}${r.description?`<p>${protoEsc(r.description)}</p>`:''}</div>`;
}
function protoHeader(){const g=protoGame,c=club(g),position=POSITIONS.find(p=>p.id===g.position)?.label??g.position;return `<section class="panel player"><div><span class="eyebrow">${g.age} anos · ${protoEsc(position)}</span><h1>${protoEsc(g.name)}</h1><p>${protoEsc(c?.name??'Formação local')}</p>${c?`<p class="competition-context">${protoEsc(protoCompetition(g))} · calendário resumido</p>`:''}${g.rival?`<p>Disputa: ${protoEsc(g.rival.name??g.rival)}${Number.isFinite(g.rival.quality)?` · nível ${protoN(g.rival.quality)}`:''}</p>`:''}</div><div class="overall"><strong>${g.age<16?'—':protoN(overall(g))}</strong><span>Overall</span></div></section>`;}
function protoLastMatches(){
 const g=protoGame,ms=g.lastMatches??[];if(!ms.length)return '';
 return `<section class="response"><div class="section-label"><span>O período em campo</span><span>${ms.length} partidas</span></div><div class="matches">${ms.map(m=>`<article class="match-detail"><div class="matchrow"><span>${protoEsc(m.opponent)}</span><span>${m.gf}–${m.ga}</span><small>${m.minutes?`${m.minutes} min · ${protoN(m.rating,1)}`:'Não entrou'}</small></div>${m.minutes?`<p class="match-evidence">${g.position==='GK'?`${m.saves} defesas · ${m.interventions} antecipações`:`${m.goals} gols · ${m.assists} assistências · ${m.chancesCreated} chances · ${m.interventions} intervenções`}</p>`:''}<p><span class="speaker">Treinador</span> · ${protoEsc(m.coach)}</p><p><span class="speaker">Torcida</span> · ${protoEsc(m.fans)}</p>${m.moment?`<p class="match-moment">${protoEsc(m.moment)}</p>`:''}</article>`).join('')}</div></section>`;
}
function protoMemories(){
 const g=protoGame,m=g.fanMemory??{},timeline=g.memoryTimeline??[];
 const recorded=new Set(timeline.map(x=>`${x.clubId}:${x.text}`));
 const current=timeline.map(x=>({text:x.text,clubId:x.clubId,context:`${x.season} anos · ${x.round?'rodada '+x.round:'fora de campo'}`}));
 const legacy=Object.entries(m).reverse().flatMap(([clubId,x])=>[...(x.criticalEntries??[]),...(x.entries??[])].filter(text=>!recorded.has(`${clubId}:${text}`)).map(text=>({text,clubId,context:''})));
 const array=[...current,...legacy];
 return array.length?`<details><summary>O futebol lembra · ${array.length} registros</summary><div class="memory-list">${array.map(x=>`<p>${protoEsc(CLUBS.find(c=>c.id===x.clubId)?.shortName??x.clubId)}${x.context?` · ${protoEsc(x.context)}`:''} · ${protoEsc(protoHumanText(x.text))}</p>`).join('')}</div></details>`:'';
}
function protoFooter(){return `<nav class="nav-actions" aria-label="Carreira do protótipo"><button class="quiet" id="proto-history">${protoPage==='history'?'Voltar ao jogo':'Minha história'}</button><button class="quiet" id="proto-export">Exportar carreira</button><button class="quiet" id="proto-reset">Recomeçar</button></nav>`;}
function protoPlay(){const g=protoGame,e=g.event;let decisionText=e.body,decisionTitle=e.title;if(e.kind==='PLAN'&&g.objective?.targetText)decisionText=decisionText.replace(g.objective.targetText+'. ','').trim();if(e.kind==='PLAN'&&g.objective?.title)decisionTitle=decisionTitle.replace(': '+g.objective.title,'');const done=e.kind==='DONE'||g.phase==='DONE';const body=done?`<section class="panel end-card"><span class="eyebrow">O recorte terminou. A carreira ainda pode ir além.</span><h1>${protoEsc(e.title)}</h1><p>${protoEsc(e.body)}</p>${protoStats(g.totalstats)}</section>`:`<section class="decision" aria-label="Decisão atual"><span class="eyebrow">${g.age<18?'Formação':`Ano ${g.season-17} de 3`} · ${protoEsc(({FORMATION:'Sua formação',RIVALRY:'Disputa por vaga',PLAN:'Projeto esportivo',DECISIVE:'Jogo importante',INTEREST:'Interesse do mercado',CONTACT:'Negociação',OFFER:'Proposta concreta',DONE:'Sua história',RECOVERY:'Retomar espaço',ASSESSMENT:'Avaliação',ASSESSMENT_RESULT:'Resposta da avaliação',RESPONSE:'Resposta ao treinador'})[e.kind]??'Sua carreira')}</span><h2>${protoEsc(decisionTitle)}</h2><p class="decision-body">${protoEsc(decisionText)}</p>${e.choices.map((c,i)=>`<button class="choice" data-proto-choice="${protoEsc(c.id)}" data-proto-event="${protoEsc(e.id)}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${protoEsc(c.label)}</strong>${c.hint?`<small>${protoEsc(c.hint)}</small>`:''}</span><span class="arrow" aria-hidden="true">›</span></button>`).join('')}</section>`;protoRoot.innerHTML=protoShell(`${protoHeader()}${protoStates()}${protoStats(g.seasonStats)}${protoEvidence()}${protoOutcome()}${protoObjective()}${protoSkillRows()}${body}${protoGoal()}${protoLastMatches()}${protoMemories()}${protoFooter()}`);protoBind();}
function protoHistory(){const g=protoGame;const records=g.history??[];const years=g.yearStats??[];protoRoot.innerHTML=protoShell(`${protoHeader()}<section class="panel"><span class="eyebrow">Seu futebol, até aqui</span>${protoStats(g.totalstats)}${years.map(y=>`<article class="timeline"><h3>${y.age} anos · ${protoEsc(CLUBS.find(c=>c.id===y.clubId)?.shortName??'Clube')}</h3>${protoStats(y)}</article>`).join('')}${(g.progression??[]).map(x=>`<article class="timeline"><h3>${x.season} anos · ${x.period?'período '+x.period:'formação'}</h3><p>Overall ${protoN(x.beforeOverall)} → ${protoN(x.afterOverall)} · experiência ${x.experienceGain>0?'+':''}${protoN(x.experienceGain,1)}</p></article>`).join('')}${(g.objectiveHistory??[]).map(o=>`<article class="timeline"><h3>${o.season} anos · período ${o.period} · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')}</h3><p>${protoEsc(o.title)} · ${o.status==='MET'?'cumprida':'não cumprida'}</p><p>${protoEsc(o.targetText)}</p><p>${protoEsc(o.progressText)}</p></article>`).join('')}${records.map(h=>`<article class="timeline"><h3>${protoEsc(h.title??h.club??h.headline??`${h.age??h.season??''} anos · ${CLUBS.find(c=>c.id===h.clubId)?.shortName??'Clube'}`)}</h3><p>${protoEsc(h.body??h.detail??h.text??h.reason??'')}</p>${h.stats?protoStats(h.stats):''}</article>`).join('')}${(g.log??[]).slice(0,20).map(x=>`<p>${protoEsc(protoHumanText(typeof x==='string'?x:x.text??x.detail??x.title??'Marco registrado'))}</p>`).join('')}</section>${(g.choicesLog??[]).map(x=>`<p class="choice-history">${x.age} anos · ${protoEsc(x.label)}</p>`).join('')}${protoMemories()}${protoClubDirectory()}${protoFooter()}`);protoBind();}
function protoBind(){document.querySelectorAll('[data-proto-choice]').forEach(b=>b.addEventListener('click',()=>{if(!protoGame||b.dataset.protoEvent!==protoGame.event.id)return;const before=Object.fromEntries(['condition','fatigue','pressure','confidence','trust'].map(k=>[k,protoGame[k]]));try{if(!choose(protoGame,b.dataset.protoChoice))return;}catch{protoError='Não foi possível concluir esta decisão. Sua carreira salva foi preservada; exporte os dados e recarregue a tela.';protoRender();return;}protoDelta=Object.fromEntries(Object.keys(before).map(k=>[k,protoGame[k]-before[k]]));protoStore();protoRender();document.querySelector('.skills')?.scrollIntoView({block:'start',behavior:'instant'});}));document.querySelector('#proto-history')?.addEventListener('click',()=>{protoPage=protoPage==='history'?'play':'history';protoRender();});document.querySelector('#proto-export')?.addEventListener('click',()=>protoDownload(JSON.stringify(protoGame,null,2),'1903-brasil-ab-carreira.json'));document.querySelector('#proto-reset')?.addEventListener('click',()=>{if(!confirm('Recomeçar apenas a carreira deste protótipo? Você pode exportá-la antes.'))return;try{localStorage.removeItem(protoKey);protoGame=null;protoRaw=null;protoDelta={};protoError='';protoPage='play';protoRender();}catch{protoError='Não foi possível apagar a carreira. Ela foi preservada.';protoRender();}});}
function protoRender(){if(!protoGame)protoStart();else if(protoPage==='history')protoHistory();else protoPlay();}
protoLoad();protoRender();
