import {CLUBS,POSITIONS,createGame,choose,overall,club,validGame,routinePreview,extendCareer,projectProfile} from './engine.mjs';
const protoRoot=document.querySelector('#app');
const protoKey='1903.prototype10.v2';
let protoGame=null,protoPage='play',protoError='',protoRaw=null,protoDelta={};
const protoEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const protoN=(v,dec=0)=>Number.isFinite(v)?Number(v).toLocaleString('pt-BR',{maximumFractionDigits:dec}):'—';
function protoLoad(){try{const raw=localStorage.getItem(protoKey);if(!raw)return;protoRaw=raw;const g=JSON.parse(raw);if(!validGame(g))throw Error('Formato inesperado');protoGame=g;}catch{protoError='Não foi possível ler a carreira deste protótipo. Os dados originais foram preservados.';}}
function protoStore(){try{localStorage.setItem(protoKey,JSON.stringify(protoGame));protoError='';}catch{protoError='O navegador não permitiu salvar. Você pode continuar nesta tela; exporte a carreira para preservá-la.';}}
function protoDownload(value,name,type='application/json'){const u=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
function protoShell(content){if(protoGame)return `<main class="game-view">${content}</main>`;return `<main class="shell"><header class="topline"><span class="wordmark">1903</span><span class="edition">BRASIL · A–D<br>PROTÓTIPO · 08</span></header>${protoError?`<p class="notice" role="status">${protoEsc(protoError)}</p>`:''}${content}</main>`;}
function protoDreamOptions(){return ['A','B','C','D'].map(division=>`<optgroup label="Série ${division}">${CLUBS.filter(c=>c.division===division).map(c=>`<option value="${c.id}"${c.id==='gremio'?' selected':''}>${protoEsc(c.name)}</option>`).join('')}</optgroup>`).join('');}
function protoCompetition(g){return g.calendarRevision===1&&g.scheduleDivision?(g.scheduleDivision==='TRANSITION'?'Circuito de transição':`Série ${g.scheduleDivision}${g.scheduleDivision==='D'&&g.scheduleGroup?' · grupo '+g.scheduleGroup+' · 18 jogos experimentais':''}`):'Calendário legado';}
function protoClubDirectory(){return `<details><summary>Os clubes do Brasil · 156 nas Séries A–D</summary>${['A','B','C','D'].map(division=>`<h3>Série ${division} · ${CLUBS.filter(c=>c.division===division).length} clubes · 2026</h3><div class="league">${CLUBS.filter(c=>c.division===division).map(c=>`<div><span>${protoEsc(c.name)} <small>${protoEsc(c.state)}${c.group?' · grupo '+protoEsc(c.group):''}</small></span><span>Nível ${c.level}</span></div>`).join('')}</div>`).join('')}<p class="scope">Participantes de 2026. Níveis, elencos e projetos são parâmetros do jogo. Calendário experimental de 18 partidas por temporada; calendário resumido, não reproduz acesso, rebaixamento ou mata-mata oficiais.</p></details>`;}
function protoProjectFacts(profile){
 if(!profile)return '';
 const chance=Number.isFinite(profile.starterChance)?`${protoN(profile.starterChance*100)}% de chance inicial de titularidade`:'';
 const minutes=profile.minutesEstimate&&Number.isFinite(profile.minutesEstimate.min)&&Number.isFinite(profile.minutesEstimate.max)?`${protoN(profile.minutesEstimate.min)}–${protoN(profile.minutesEstimate.max)} min/jogo previstos${profile.recruitment==='PROSPECT'?' · média inclui banco':''}`:'';
 return `<div class="project-facts">${[profile.recruitment==='PROSPECT'?'Aposta no seu desenvolvimento':'',profile.division?(profile.division==='REGIONAL'?'Circuito de transição':`Série ${profile.division}${profile.group?' · grupo '+profile.group:''}`):'',chance,minutes].filter(Boolean).map(x=>`<span>${protoEsc(x)}</span>`).join('')}</div>`;
}
const protoShortCosts={
 'formation:technique':['Execução técnica na função.','Menos leitura e físico; mais carga.'],
 'formation:reading':['Leitura de jogo e experiência.','Menos técnica; mais carga mental.'],
 'formation:athletic':['Velocidade e força nos duelos.','Menos técnica; mais desgaste físico.'],
 'formation:balanced':['Escola, lazer e recuperação.','Menos prática técnica.'],
 'rival:earn':['Prática para disputar a vaga.','Mais fadiga.'],
 'rival:team':['Mais cooperação e construção.','Menos finalizações próprias.'],
 'rival:challenge':['Mais presença ofensiva.','Mais pressão e exigência.'],
 'recovery:EXTRA':['Mais prática da habilidade principal.','Sobrecarga pode reduzir habilidades.'],
 'recovery:READ':['Mais leitura de jogo.','Menos prática principal; mais carga mental.'],
 'recovery:COOPERATE':['Mais passe e cooperação.','Menos finalizações próprias.'],
 'decisive:risk':['Mais criação.','Mais exposição e desgaste.'],
 'decisive:safe':['Mais proteção.','Menos protagonismo.'],
 'market:stay':['Mantém adaptação e espaço.','Abre mão do outro projeto.'],
 'intent:ATTACK':['Mais acesso ao chute.','Menos defesa; mais desgaste.'],
 'intent:CREATE':['Mais criação para o time.','Menos chutes próprios.'],
 'intent:CONTROL':['Mais passe e menor carga.','Menos desmarques e chutes.'],
 'intent:SAFE':['Mais segurança e menor carga.','Menos construção.'],
 'intent:BUILD':['Mais criação na saída.','Erro de passe expõe o gol.'],
 'intent:SWEEP':['Mais antecipações.','Falhas expõem o gol; mais carga.'],
 'intent:HOLD':['Mais proteção do setor.','Menos apoio ofensivo.'],
 'intent:ADVANCE':['Mais apoio e progressão.','Deixa espaço; mais desgaste.'],
 'intent:LINK':['Mais criação coletiva.','Menos chutes próprios.'],
 'intent:PRESS':['Mais recuperação de bola.','Mais carga; menos finalização.'],
 'routine:TRAIN':['128% da prática habitual.','Menos descanso e felicidade; mais stress.'],
 'routine:REST':['Recupera corpo e stress.','Só 50% da prática de treino.'],
 'routine:LIFE':['Mais felicidade; menos stress.','Só 58% da prática; menos recuperação física.']
};
const protoMetricNames={attack:'chutes no alvo + gols',creation:'chances criadas',control:'passes completos',protection:'ações defensivas',sweep:'antecipações',press:'recuperações',advance:'progressões',cooperation:'ações coletivas'};
function protoTargetLine(o){const t=o?.target;if(!t)return '';return [`${t.apps} ${t.apps===1?'jogo':'jogos'}`,`${t.minutes} min`,t.good?`${t.good} ${t.good===1?'boa':'boas'}`:'',`${t.output} ${protoMetricNames[o.metric]??'ações'}`].filter(Boolean).join(' · ');}
function protoChoiceCard(c,i,g,e){
 const bare=c.id.split('@')[0],id=bare.split(':')[1];
 const profile=c.profile??(e.kind==='ENTRY'?g.entryOffers?.find(x=>x.clubId===id):e.kind==='OFFER'&&bare.startsWith('accept:')?g.offer?.profile:null);
 const compact=protoShortCosts[bare],sport=c.action?protoShortCosts['intent:'+c.action.intent]:null;
 const routineGain={TRAIN:'prática intensa',WORK:'prática moderada',REST:'recuperação física',LIFE:'tempo pessoal'},routineCost={TRAIN:'Carga extra; menos descanso e lazer.',WORK:'Menos prática que treino extra.',REST:'Metade da prática de treino.',LIFE:'Menos treino; menor recuperação física.'};
 const benefit=c.action?`${(sport?.[0]??c.benefit).replace(/\.$/,'')}; ${routineGain[c.action.routine]}.`:compact?.[0]??c.benefit,cost=c.action?`${routineCost[c.action.routine]} ${sport?.[1]??''}`:compact?.[1]??c.cost;
 const target=c.action?.objective?protoTargetLine(c.action.objective):c.hint?.match(/Meta do papel: .*/)?.[0];
 const contract=profile?`<div class="project-facts"><span>Série ${protoEsc(profile.division)} · treino ${protoN(profile.trainingQuality)}</span><span>R$ ${protoN(profile.monthly)}/mês</span><span>${protoN(profile.starterChance*100)}% chance inicial · ${protoN(profile.minutesEstimate?.min)}–${protoN(profile.minutesEstimate?.max)} min/jogo previstos</span></div><small class="choice-benefit"><span>Ganha</span> ${protoEsc(profile.recruitment==='PROSPECT'?'Aposta no desenvolvimento; entradas curtas.':profile.role)}</small><small class="choice-cost"><span>Custo</span> Rival ${protoN(profile.rivalQuality)} · cobrança ${protoN(profile.pressure)}${e.kind==='INTEREST'?' · pode não haver proposta':''}</small>`:'';
 return `<button class="choice" data-proto-choice="${protoEsc(c.id)}" data-proto-event="${protoEsc(e.id)}" aria-label="${protoEsc(c.label)}"><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${protoEsc(c.label)}</strong>${contract||`${benefit?`<small class="choice-benefit"><span>Ganha</span> ${protoEsc(benefit)}</small>`:''}${cost?`<small class="choice-cost"><span>Custo</span> ${protoEsc(cost)}</small>`:''}`}${target?`<small class="choice-target">${c.action?'Meta: ':''}${protoEsc(target)}</small>`:''}</span><span class="arrow" aria-hidden="true">›</span></button>`;
}
function protoContract(){
 const g=protoGame,c=club(g);if(!c)return '';
 const profile=g.clubProject;
 const salary=Number.isFinite(g.salary)?`R$ ${protoN(g.salary)}/mês`:'Remuneração não registrada neste vínculo';
 const context=profile&&Number.isFinite(profile.trainingQuality)?`Estrutura de formação ${protoN(profile.trainingQuality)}/100`:'';
 const live=profile?.recruitment==='PROSPECT'?projectProfile(g,c.id):null;
 return `<p class="contract-line">${protoEsc(salary)}${context?` · ${protoEsc(context)}`:''}</p>${g.scheduleDivision==='D'?`<p class="scope">${protoEsc(protoCompetition(g))} · calendário resumido</p>`:''}${live?`<p class="scope">Contratado como promessa · ${protoEsc(live.role)}. Previsão atual: ${protoN(live.starterChance*100)}% de titularidade; ${protoN(live.minutesEstimate.min)}–${protoN(live.minutesEstimate.max)} min por jogo, incluindo o banco. Espaço depende da evolução e das atuações neste clube.</p>`:''}`;
}
function protoStart(){protoRoot.innerHTML=protoShell(`<section class="intro"><span class="eyebrow">Um campo. Muitas possibilidades.</span><h1>Conquiste espaço.<br>Faça o jogo lembrar.</h1><p class="start-copy">Descubra seu jogo na formação. Escolha entre os clubes interessados e construa uma carreira com ganhos, custos e disputa por espaço.</p></section><form class="panel start-form" id="proto-start"><label>Nome do jogador<input name="name" maxlength="35" placeholder="Seu nome" required autocomplete="off"></label><label>Minha primeira posição<select name="position">${POSITIONS.map(p=>`<option value="${p.id}"${p.id==='ST'?' selected':''}>${protoEsc(p.label)}</option>`).join('')}</select></label><label>Meu clube dos sonhos<select name="dream">${protoDreamOptions()}</select></label><button class="primary" type="submit">Começar minha história</button></form><p class="scope">Recorte rápido, encerrado aos 25 anos. Clubes e divisões de 2026; calendário resumido e elencos simulados. Sua carreira deste protótipo continua no mesmo save.</p>${protoRaw&&!protoGame?'<button class="quiet" id="proto-recovery">Baixar os dados preservados</button><button class="quiet" id="proto-new">Começar outra carreira</button>':''}`);document.querySelector('#proto-start')?.addEventListener('submit',e=>{e.preventDefault();if(protoRaw&&!protoGame){protoError='Baixe os dados preservados antes de iniciar outra carreira neste navegador.';protoRender();return;}const f=new FormData(e.currentTarget);protoGame=createGame(String(f.get('name')).trim()||'Jogador',String(f.get('position')));protoGame.dreamClubId=String(f.get('dream'));protoStore();protoRender();});document.querySelector('#proto-recovery')?.addEventListener('click',()=>protoDownload(protoRaw,'1903-prototipo02-recuperacao.json'));document.querySelector('#proto-new')?.addEventListener('click',()=>{if(!confirm('Preservar os dados ilegíveis em uma cópia neste navegador e começar outra carreira?'))return;try{localStorage.setItem(protoKey+'.recovery.'+Date.now(),protoRaw);protoRaw=null;protoError='Cópia preservada neste navegador. Você pode criar outra carreira.';protoRender();}catch{protoError='Não foi possível preservar a cópia. Baixe os dados antes de tentar novamente.';protoRender();}});}
function protoStates(){
 const g=protoGame;
 const card=(key,label,inverse,value=g[key],delta=protoDelta[key])=>{
  const known=Number.isFinite(value),tone=!known?'':inverse?(value<=30?'good':value<=60?'warn':'bad'):(value>=70?'good':value>=40?'warn':'bad');
  const changed=Number.isFinite(delta)&&Math.abs(delta)>=.1,d=changed?`${delta>0?'+':''}${protoN(delta,1)}`:'—';
  const favorable=changed&&(inverse?delta<0:delta>0);
  return `<div class="state" role="group" aria-label="${label}: ${known?protoN(value)+' de 100':'ainda não registrado'}; ${inverse?'menor':'maior'} é melhor. Variação ${d}" title="${known?(inverse?'Menor é melhor':'Maior é melhor'):'Registrado a partir da próxima etapa atualizada'}"><span>${label}</span><strong class="${tone}">${known?protoN(value):'—'}</strong><small class="${changed?(favorable?'good':'bad'):''}">${d}</small></div>`;
 };
 const rest=Number.isFinite(g.fatigue)?100-g.fatigue:undefined,restDelta=Number.isFinite(protoDelta.fatigue)?-protoDelta.fatigue:undefined;
 return `<section class="hud" aria-label="Condição do jogador"><div class="wellbeing-states" aria-label="Bem-estar: desenvolvimento e atuação">${card('happiness','Felicidade',false)}${card('rest','Descanso físico',false,rest,restDelta)}${card('mentalStress','Stress mental',true)}</div><div class="sport-states">${card('condition','Condição',false)}${card('pressure','Cobrança',true)}${card('confidence','Confiança',false)}${card('trust','Treinador',false)}</div></section>`;
}
const protoIntentLabels={CREATE:'criar oportunidades',ATTACK:'buscar o gol',CONTROL:'controlar o ritmo',LINK:'conectar o ataque',PRESS:'pressionar',SAFE:'proteger o gol',BUILD:'iniciar a construção',SWEEP:'cobrir a profundidade',HOLD:'proteger o setor',ADVANCE:'avançar',EXTRA:'treino extra',READ:'estudar o jogo',COOPERATE:'trabalhar com o grupo'};
const protoHumanText=v=>String(v??'').replace(/\b(CREATE|ATTACK|CONTROL|LINK|PRESS|SAFE|BUILD|SWEEP|HOLD|ADVANCE|EXTRA|READ|COOPERATE)\b/g,k=>protoIntentLabels[k]);
const protoSkills={finishing:'Finalização',passing:'Passe',reading:'Leitura',pace:'Velocidade',defending:'Defesa',goalkeeping:'Goleiro'};
function protoProgressSpan(p){return !p?'':p.period===0?`${p.season}–${p.season+2} anos · 2 anos de formação`:`${p.season} anos · bloco de 6 partidas`; }
function protoSkillRows(){const g=protoGame,span=protoProgressSpan(g.progression?.at(-1));return `<section class="panel"><div class="section-label" style="margin-top:0"><span>Habilidades adquiridas</span><span>Escala adulta · 0–99</span></div>${span?`<p class="skill-period">Variação acumulada · ${protoEsc(span)}</p>`:'<p class="skill-period">Pontos na escala adulta; desenvolvimento inicial.</p>'}<div class="skills">${Object.entries(protoSkills).map(([key,label])=>{const val=g.skills[key],ref=g.age<18?g.age<14?25:40:55,tone=val>=ref+8?'good':val<ref-8?'bad':'warn';return `<div class="skill ${tone}" title="${protoEsc(label)}: ${protoN(val,1)}. Referência deste recorte ${ref}; não é potencial."><div class="skill-row"><span>${label}</span><span class="skill-value"><strong>${protoN(val,1)}</strong>${Number.isFinite(g.progression?.at(-1)?.skillChanges?.[key])&&Math.abs(g.progression.at(-1).skillChanges[key])>=.05?`<small class="${g.progression.at(-1).skillChanges[key]<0?'bad':'good'}" title="Variação no último avanço · ${protoEsc(span)} · pontos na escala">${g.progression.at(-1).skillChanges[key]>0?'+':''}${protoN(g.progression.at(-1).skillChanges[key],1)}</small>`:''}</span></div><div class="bar" aria-hidden="true"><i style="width:${Math.min(99,Math.max(0,val))}%"></i></div></div>`;}).join('')}</div></section>`;}
function protoStats(s){if(!s)return '';return `<div class="statline" aria-label="Estatísticas observadas"><div><strong>${protoN(s.apps)}</strong>jogos</div><div><strong>${protoN(s.starts)}</strong>titular</div><div><strong>${protoN(s.minutes)}</strong>minutos</div><div><strong>${protoN(s.goals)}</strong>gols</div><div><strong>${protoN(s.assists)}</strong>assistências</div><div><strong>${s.apps?protoN(s.ratingSum/s.apps,1):'—'}</strong>nota</div></div>`;}
function protoGoal(){const g=protoGame,dream=CLUBS.find(c=>c.id===g.dreamClubId);return dream?`<p class="dream">${g.clubId===dream.id?'Você chegou ao clube dos seus sonhos. Agora precisa conquistar seu lugar.':`Seu destino desejado: ${protoEsc(dream.shortName)}.`}</p>`:'';}
function protoObjective(){
 const g=protoGame,o=g.objective;if(g.phase==='ENTRY'||g.age>=18&&!o?.metric)return '';if(!o||typeof o!=='object')return '';
 const archived=o.season&&(o.season!==g.season||o.clubId!==g.clubId);
 const context=archived?`<p class="eyebrow">${o.season} anos · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')} · meta anterior</p>`:'';
 const pendingRole=o.revision===1&&o.status==='ACTIVE',duplicate=o.status!=='ACTIVE'&&g.lastOutcome?.season===o.season&&g.lastOutcome?.clubId===o.clubId;
 const labels={ACTIVE:'Em disputa',MET:'Meta cumprida',MISSED:'Meta não cumprida'};
 const progress=o.progressText??Object.entries(o.progress??{}).filter(([k])=>k!=='current').map(([k,v])=>`${protoN(v)} ${{apps:'jogos',minutes:'min',good:'boas atuações',output:'ações da função'}[k]??k}`).join(' · ');
 const target=pendingRole?`${o.target.apps} participações, ${o.target.minutes} minutos e ${o.target.good} boas atuações. A produção exigida muda com o papel escolhido abaixo.`:o.targetText;
 return `<section class="objective-card" aria-label="Objetivo do treinador">${context}<div class="section-label"><span>${protoEsc(pendingRole?'A prova dos próximos seis jogos':o.title)}</span><span class="${o.status==='MET'?'good':o.status==='MISSED'?'warn':''}">${labels[o.status]??'Em disputa'}</span></div>${o.body&&!duplicate?`<p>${protoEsc(o.body)}</p>`:''}${target?`<p class="target">${protoEsc(target)}</p>`:''}${!duplicate&&!pendingRole?`<p class="objective-progress">${protoEsc(progress)}</p>`:''}</section>`;
}
function protoOutcome(){
 const g=protoGame,o=g.lastOutcome;
 const outcomeBody=String(o?.body??'').replace(/^Etapa dos (12|14|16) anos:/,(_,age)=>`Formação dos ${age} aos ${Number(age)+2} anos (2 anos):`);
 if(!o&&!g.coachReaction&&!g.fanReaction)return '';
 const context=o?.season&&(o.season!==g.season||o.clubId!==g.clubId)?`<p class="eyebrow">${o.season} anos · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')} · resultado anterior</p>`:'';
 return `<section class="outcome">${context}${o?`<h3>${protoEsc(o.title)}</h3><p>${protoEsc(outcomeBody)}</p>`:''}${g.coachReaction?`<p><span class="speaker">Treinador</span> · ${protoEsc(g.coachReaction)}</p>`:''}${g.fanReaction?`<p><span class="speaker">Torcida</span> · ${protoEsc(g.fanReaction)}</p>`:''}</section>`;
}
function protoEvidence(){
 const g=protoGame,r=g.roleEvidence;if(!r||!r.minutes)return '';
 const intent=g.lastMatches?.[0]?.strategy;
 const byIntent={SAFE:['saves','goalsConceded'],SWEEP:['interventions','goalsConceded'],BUILD:['completedPasses','chancesCreated'],HOLD:['interventions','failedInterventions'],ADVANCE:['progressions','chancesCreated'],ATTACK:['shotsOnTarget','goals'],LINK:['chancesCreated','assists'],PRESS:['interventions','progressions'],CREATE:['chancesCreated','keyPasses'],CONTROL:['completedPasses','chancesCreated']};
 const keys=byIntent[intent]??(g.position==='GK'?['saves','interventions']:['CB','FB','DM'].includes(g.position)?['interventions','completedPasses']:['AM','CM'].includes(g.position)?['chancesCreated','completedPasses']:['goals','chancesCreated']);
 const labels={saves:'defesas',goalsConceded:'gols sofridos em campo',interventions:g.position==='GK'?'antecipações':'intervenções',failedInterventions:'intervenções falhas',completedPasses:'passes completos',chancesCreated:'chances criadas',keyPasses:'passes decisivos',goals:'gols',assists:'assistências',shotsOnTarget:'finalizações no alvo',progressions:'progressões'};
 const value=k=>r[k]??g.lastMatches.reduce((sum,m)=>sum+(m[k]??0),0);
 return `<div class="role-evidence" aria-label="Contribuição no período">${keys.map(k=>`<span><strong>${protoN(value(k))}</strong> ${labels[k]}</span>`).join('')}${r.description?`<p>${protoEsc(r.description)}</p>`:''}</div>`;
}
function protoShotContext(){
 const g=protoGame,ms=g.lastMatches??[];if(!ms.length||g.position==='GK')return '';
 const total=k=>ms.reduce((sum,m)=>sum+(m[k]??0),0);
 const opportunities=total('shotOpportunity'),shots=total('shots'),onTarget=total('shotsOnTarget'),goals=total('goals'),minutes=total('minutes');
 if(!minutes)return '<p class="shot-context">Sem minutos neste período: sua finalização não foi testada em campo.</p>';
 let explanation=shots===0?'Sem chute: a finalização não chegou a ser testada. Minutos, função, abastecimento e movimentos sem bola limitam as oportunidades.':goals===0?`${shots} chutes, ${onTarget} no alvo; nenhum gol. Finalização melhora a execução, mas não elimina a defesa adversária nem garante conversão.`:`${shots} chutes, ${onTarget} no alvo e ${goals} gols. A produção dependeu de oportunidade e execução.`;
 if(ms.some(m=>Number.isFinite(m.shotOpportunity)))explanation+=` ${opportunities} ataques do time com você em campo. Nem todos viram uma chance sua de chute.`;
 return `<p class="shot-context">${protoEsc(explanation)}</p>`;
}
function protoMarketHistory(){
 const g=protoGame,rows=g.marketHistory??[];if(!rows.length)return '';
 const states={OBSERVED:'Interesse recebido',CONTACT:'Contato aberto',NO_OFFER:'Contato sem proposta',ACCEPTED:'Contrato aceito',STAY:'Escolheu permanecer'};
 return `<section class="market-history"><h3>Quem observou sua carreira</h3>${rows.map(row=>`<article class="timeline"><h3>${protoEsc(row.season)} anos · ${protoEsc(states[row.status]??'Janela registrada')}</h3>${(row.contacts??[]).length?row.contacts.map(x=>{const c=CLUBS.find(c=>c.id===x.clubId);return `<p>${protoEsc(c?.name??x.clubId)}${c?` · ${protoEsc(c.divisionLabel)}`:''}${row.selectedClubId===x.clubId?' · contato escolhido':''}</p>`;}).join(''):'<p>Nenhum contato surgiu nesta janela.</p>'}${(row.contacts??[]).some(x=>x.profile?.recruitment==='PROSPECT')?'<p class="scope">Observação como promessa: o clube viu evolução, com entrada gradual prevista.</p>':''}<p class="scope">Interesse não garante proposta nem contrato.</p></article>`).join('')}</section>`;
}
function protoLastMatches(){
 const g=protoGame,ms=g.lastMatches??[];if(!ms.length)return '';
 return `<section class="response"><div class="section-label"><span>O período em campo</span><span>${ms.length} partidas</span></div><div class="matches">${ms.map(m=>`<article class="match-detail"><div class="matchrow"><span>${protoEsc(m.opponent)}</span><span>${m.gf}–${m.ga}</span><small>${m.minutes?`${m.minutes} min · ${protoN(m.rating,1)}`:'Não entrou'}</small></div>${m.minutes?`<p class="match-evidence">${g.position==='GK'?`${m.saves} defesas · ${m.interventions} antecipações`:`${m.shots} chutes · ${m.shotsOnTarget} no alvo · ${m.goals} gols · ${m.assists} assistências · ${m.chancesCreated} chances`}</p>`:''}<p><span class="speaker">Treinador</span> · ${protoEsc(m.coach)}</p><p><span class="speaker">Torcida</span> · ${protoEsc(m.fans)}</p>${m.moment?`<p class="match-moment">${protoEsc(m.moment)}</p>`:''}</article>`).join('')}</div></section>`;
}
function protoMemories(){
 const g=protoGame,m=g.fanMemory??{},timeline=g.memoryTimeline??[];
 const recorded=new Set(timeline.map(x=>`${x.clubId}:${x.text}`));
 const current=timeline.map(x=>({text:x.text,clubId:x.clubId,context:`${x.season} anos · ${x.round?'rodada '+x.round:'fora de campo'}`}));
 const legacy=Object.entries(m).reverse().flatMap(([clubId,x])=>[...(x.criticalEntries??[]),...(x.entries??[])].filter(text=>!recorded.has(`${clubId}:${text}`)).map(text=>({text,clubId,context:''})));
 const array=[...current,...legacy];
 return array.length?`<details><summary>O futebol lembra · ${array.length} registros</summary><div class="memory-list">${array.map(x=>`<p>${protoEsc(CLUBS.find(c=>c.id===x.clubId)?.shortName??x.clubId)}${x.context?` · ${protoEsc(x.context)}`:''} · ${protoEsc(protoHumanText(x.text))}</p>`).join('')}</div></details>`:'';
}
function protoResultSummary(){
 const g=protoGame,last=g.choicesLog?.at(-1),ms=g.lastMatches??[];
 if(!last)return '';
 const simulated=last.kind==='PLAN'&&ms.length>0,total=k=>ms.reduce((n,m)=>n+(m[k]??0),0),part=ms.filter(m=>m.minutes>0);
 if(simulated){const wins=ms.filter(m=>m.result==='W').length,losses=ms.filter(m=>m.result==='L').length,o=g.objectiveHistory?.findLast(o=>o.season===ms[0].season&&o.clubId===ms[0].clubId&&o.period===Math.ceil(ms[0].round/6))??g.objective;
  const goal=o?.status==='MET'?'meta cumprida':o?.status!=='MISSED'?'':o.revision===2&&o.progress.minutes<o.target.minutes?'amostra incompleta':o.revision===2&&o.progress.good>=Math.max(1,o.target.good)?'bom período · meta parcial':'meta não cumprida';
  return `<section class="result-summary" aria-label="Efeito da última decisão"><span class="eyebrow">${ms[0].season} anos · últimos ${ms.length} jogos</span><div class="result-numbers"><span>${total('goals')} gols</span><span>${total('assists')} assistências</span><span>${total('minutes')} min</span></div><p><span class="speaker">Treinador</span> · ${part.filter(m=>m.good||m.exceptional).length}/${part.length} boas atuações${goal?' · '+goal:''}${Number.isFinite(o?.progress?.output)?` (${o.progress.output}/${o.target.output} ${protoMetricNames[o.metric]??'ações'})`:''}.</p><p><span class="speaker">Torcida</span> · ${wins} vitórias, ${losses} derrotas · respeito ${protoN(g.fanMemory[ms[0].clubId]?.respect)}.</p></section>`;
 }
 let detail=last.kind==='FORMATION'?`OVR ${protoN(g.progression?.at(-1)?.beforeOverall)} → ${protoN(g.progression?.at(-1)?.afterOverall)} · ${g.age} anos`:
 last.kind==='ENTRY'||last.kind==='OFFER'&&last.id.startsWith('accept:')?`${club(g)?.shortName??'Clube'} · treino ${protoN(g.clubProject?.trainingQuality)} · R$ ${protoN(g.salary)}/mês`:
 last.kind==='CONTACT'&&g.event.kind==='OFFER'?'Proposta recebida. Compare os minutos e a cobrança.':last.kind==='CONTACT'&&g.event.kind==='ASSESSMENT_RESULT'?'A negociação terminou sem contrato.':last.kind==='ROUTINE'?'Rotina definida. Escolha seu papel em campo.':'';
 return detail?`<section class="result-summary" aria-label="Efeito da última decisão"><p>${protoEsc(detail)}</p></section>`:'';
}
function protoSeasonRows(){
 const g=protoGame,rows=(g.yearStats??[]).map(y=>({...y,partial:false}));
 if(g.phase==='PRO'&&!rows.some(y=>y.season===g.season)&&g.playedMatches.some(m=>m.season===g.season))rows.push({age:g.season,season:g.season,clubId:g.clubId,...g.seasonStats,partial:true});
 return rows.map(y=>({...y,ovr:(g.progression??[]).filter(p=>p.season===y.season&&p.period>0).at(-1)?.afterOverall}));
}
function protoSeasonEvolution(){
 const rows=protoSeasonRows();if(!rows.length)return '<p class="scope">A evolução por temporada aparece depois dos primeiros jogos profissionais.</p>';
 const points=rows.filter(y=>Number.isFinite(y.ovr)),x=i=>points.length>1?26+i*270/(points.length-1):160,y=v=>92-v*.72;
 const chart=points.length?`<svg class="evolution-chart" viewBox="0 0 322 116" role="img" aria-label="Overall registrado por temporada: ${protoEsc(points.map(p=>p.age+' anos, '+p.ovr).join('; '))}">${[20,50,80].map(v=>`<path d="M26 ${y(v)} H300" stroke="var(--line)"/><text x="2" y="${y(v)+3}">${v}</text>`).join('')}<polyline points="${points.map((p,i)=>x(i)+','+y(p.ovr)).join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.ovr)}" r="3" fill="var(--accent)"/><text x="${x(i)}" y="110" text-anchor="middle">${p.age}</text>`).join('')}</svg>`:'';
 return `<section class="season-evolution"><h2>Evolução por temporada</h2><p class="scope">Overall ao fim de cada temporada; ano em andamento é parcial.</p>${chart}<table><caption>Jogos, gols, assistências, nota e overall por temporada</caption><thead><tr><th scope="col">Temporada</th><th scope="col">J</th><th scope="col">G</th><th scope="col">A</th><th scope="col">Nota</th><th scope="col">OVR</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${r.age} anos${r.partial?' · parcial':''}<small>${protoEsc(CLUBS.find(c=>c.id===r.clubId)?.shortName??'Clube')}</small></th><td>${protoN(r.apps)}</td><td>${protoN(r.goals)}</td><td>${protoN(r.assists)}</td><td>${r.apps?protoN(r.ratingSum/r.apps,1):'—'}</td><td>${protoN(r.ovr)}</td></tr>`).join('')}</tbody></table></section>`;
}
function protoFixedHeader(){
 const g=protoGame,c=club(g),position=POSITIONS.find(p=>p.id===g.position)?.label??g.position,ms=g.lastMatches??[];

 return `<header class="game-header">${protoError?`<p class="notice" role="status">${protoEsc(protoError)}</p>`:''}<div class="identity-line"><div><h1 title="${protoEsc(g.name)}">${protoEsc(g.name)}</h1><p>${g.age} anos · ${protoEsc(position)} · ${protoEsc(c?.shortName??(g.phase==='ENTRY'?'Escolha seu primeiro clube':'Formação'))}</p></div><div class="identity-rating"><strong>${g.age<16?'—':protoN(overall(g))}</strong><small>OVR</small></div></div><div class="club-strip"><span>${c?protoEsc(g.scheduleDivision==='D'?'Série D · grupo '+g.scheduleGroup:protoCompetition(g)):'1903 · formação'}</span>${c?`<span title="Estrutura de formação do clube atual">Treino ${protoN(g.clubProject?.trainingQuality)}/100</span>`:''}<span>08</span></div>${c?`<div class="season-strip"><span>${g.season} anos · temporada</span>${protoStats(g.seasonStats)}</div>`:''}${protoStates()}<div class="header-skills">${protoSkillRows()}</div></header>`;
}
function protoFooter(){return `<footer class="game-footer"><nav class="nav-actions" aria-label="Carreira do protótipo"><button class="quiet" id="proto-history">${protoPage==='history'?'Jogo':'Carreira'}</button><button class="quiet" id="proto-matches">${protoPage==='matches'?'Jogo':'Partidas'}</button><button class="quiet" id="proto-export">Exportar</button><button class="quiet" id="proto-reset">Recomeçar</button></nav></footer>`;}
function protoMomentContext(g,e){
 const situation=e.choices[0]?.action?.situation;if(!situation)return e.body;
 const matches=g.lastMatches??[],starts=matches.filter(m=>m.started).length,mins=matches.reduce((n,m)=>n+m.minutes,0),lost=matches.filter(m=>m.result==='L').length,good=matches.filter(m=>m.good||m.exceptional).length;
 const next=g.schedule?.slice(g.round,g.round+2).map(id=>CLUBS.find(c=>c.id===id)?.shortName).filter(Boolean).join(' e '),rival=`${g.rival.name} (nível ${protoN(g.rival.quality,1)})`;
 const text={ARRIVAL:`Você disputa espaço com ${rival}. A estreia será contra ${next}.`,CHANGE:`A vaga reabre contra ${rival}. O novo clube começa diante de ${next}.`,FATIGUE:`Foram ${mins} minutos no último período. O desgaste pesa na execução; agora vêm ${next}.`,STRESS:`A cobrança pesa na execução e no aprendizado. Próximos adversários: ${next}.`,LIFE:`Sua felicidade caiu; o futebol tomou espaço da vida pessoal. Próximos adversários: ${next}.`,BENCH:`Só ${mins} minutos nos últimos seis jogos. A disputa segue com ${rival}.`,DROUGHT:`A produção ficou abaixo do papel combinado. ${next} são os próximos testes.`,DEFEAT:`${lost} derrotas nos últimos seis jogos. Agora vêm ${next}.`,STRONG:`${next} abrem uma sequência de adversários mais fortes. Quanto risco cabe no seu papel?`,STREAK:`${good} boas atuações ampliaram a exigência. ${next} testam a consistência.`,CONSOLIDATE:`Você começou ${starts} dos últimos seis jogos. Sustente espaço contra ${next}.`,DISPUTE:`${rival} segue na disputa. Você começou ${starts} dos últimos seis jogos; agora vêm ${next}.`};
 return text[situation]??e.body;
}
function protoPlay(){const g=protoGame,e=g.event;let decisionText=e.kind==='ENTRY'?'Compare previsão de minutos, treino e cobrança. A vaga não é garantida.':protoMomentContext(g,e),decisionTitle=e.title;if(e.kind==='FORMATION'){decisionTitle=`Plano de formação · ${g.age}–${g.age+2} anos`;decisionText='Escolha o foco para estes dois anos de formação.';}if(e.kind==='ROUTINE'){const team=club(g)?.shortName??'seu clube';decisionText=g.mentalStress>=60?`A cobrança no ${team} está pesando. Você pode reduzir o treino entre os próximos seis jogos para aliviar o stress, mas terá menos prática da função.`:g.fatigue>=50?`A carga reduziu seu descanso físico. Poupar treino entre os próximos seis jogos ajuda a recuperar energia, enquanto o concorrente continua trabalhando.`:g.happiness<45?`O futebol está consumindo seu tempo e sua felicidade caiu. Preservar espaço para a vida pode ajudar, com menos treino para disputar a vaga.`:`Há seis jogos pela frente. Você pode reforçar o treino, poupar sessões para recuperar o corpo ou reservar tempo para a vida. Compare prática, descanso e stress antes de escolher.`;}if(e.kind==='PLAN'&&g.objective?.targetText)decisionText=decisionText.replace(g.objective.targetText+'. ','').trim();if(e.kind==='PLAN'&&g.objective?.title)decisionTitle=decisionTitle.replace(': '+g.objective.title,'');const done=e.kind==='DONE'||g.phase==='DONE';const body=done?`<section class="panel end-card"><span class="eyebrow">O recorte terminou. A carreira ainda pode ir além.</span><h1>${protoEsc(e.title)}</h1><p>${protoEsc(e.body)}</p>${protoStats(g.totalstats)}${g.age===21?'<button class="primary" id="proto-extend">Continuar até os 25 anos</button>':''}</section>`:`<section class="decision" aria-label="Decisão atual"><span class="eyebrow">${g.age<18?'Formação':`Ano ${g.season-17} de ${(g.careerEndAge??21)-18}`} · ${protoEsc(({FORMATION:'Sua formação',ROUTINE:'Rotina antes das partidas',ENTRY:'Primeiro contrato',RIVALRY:'Disputa por vaga',PLAN:'Próximos seis jogos',DECISIVE:'Jogo importante',INTEREST:'Interesse do mercado',CONTACT:'Negociação',OFFER:'Proposta concreta',DONE:'Sua história',RECOVERY:'Retomar espaço',ASSESSMENT:'Avaliação',ASSESSMENT_RESULT:'Resposta da avaliação',RESPONSE:'Resposta ao treinador'})[e.kind]??'Sua carreira')}${e.choices[0]?.action?.objective?.title?' · '+protoEsc(e.choices[0].action.objective.title):''}</span><h2>${protoEsc(decisionTitle)}</h2><p class="decision-body">${protoEsc(decisionText)}</p>${e.choices.map((c,i)=>protoChoiceCard(c,i,g,e)).join('')}</section>`;protoRoot.innerHTML=protoShell(`${protoFixedHeader()}<div class="game-body"><div class="turn-result" aria-label="Resultado do último avanço">${protoResultSummary()}</div>${body}${done?protoSeasonEvolution():''}</div>${protoFooter()}`);protoBind();}
function protoHistory(){const g=protoGame;const records=g.history??[];const years=g.yearStats??[];protoRoot.innerHTML=protoShell(`${protoFixedHeader()}<div class="game-body">${protoContract()}${protoSeasonEvolution()}<section class="panel"><span class="eyebrow">Seu futebol, até aqui</span>${protoStats(g.totalstats)}${(g.progression??[]).map(x=>`<article class="timeline"><h3>${protoEsc(protoProgressSpan(x))}${x.period?' · período '+x.period:''}</h3><p>Overall ${protoN(x.beforeOverall)} → ${protoN(x.afterOverall)} · experiência ${x.experienceGain>0?'+':''}${protoN(x.experienceGain,1)}</p></article>`).join('')}${(g.objectiveHistory??[]).map(o=>`<article class="timeline"><h3>${o.season} anos · período ${o.period} · ${protoEsc(CLUBS.find(c=>c.id===o.clubId)?.shortName??'Formação')}</h3><p>${protoEsc(o.title)} · ${o.status==='MET'?'cumprida':'não cumprida'}</p><p>${protoEsc(o.targetText)}</p><p>${protoEsc(o.progressText)}</p></article>`).join('')}${records.map(h=>`<article class="timeline"><h3>${protoEsc(h.title??h.club??h.headline??`${h.age??h.season??''} anos · ${CLUBS.find(c=>c.id===h.clubId)?.shortName??'Clube'}`)}</h3><p>${protoEsc(h.body??h.detail??h.text??h.reason??'')}</p>${h.stats?protoStats(h.stats):''}</article>`).join('')}${(g.log??[]).slice(0,20).map(x=>`<p>${protoEsc(protoHumanText(typeof x==='string'?x:x.text??x.detail??x.title??'Marco registrado'))}</p>`).join('')}</section>${(g.choicesLog??[]).map(x=>`<p class="choice-history">${x.age} anos · ${protoEsc(x.label)}</p>`).join('')}${protoMemories()}${protoMarketHistory()}${protoClubDirectory()}</div>${protoFooter()}`);protoBind();}
function protoBind(){document.querySelector('#proto-extend')?.addEventListener('click',()=>{const next=extendCareer(protoGame);if(!next)return;protoGame=next;protoDelta={};protoPage='play';protoStore();protoRender();});document.querySelectorAll('[data-proto-choice]').forEach(b=>b.addEventListener('click',()=>{if(!protoGame||b.dataset.protoEvent!==protoGame.event.id)return;const before=Object.fromEntries(['condition','fatigue','pressure','confidence','trust','happiness','mentalStress'].map(k=>[k,protoGame[k]]));try{if(!choose(protoGame,b.dataset.protoChoice))return;}catch{protoError='Não foi possível concluir esta decisão. Sua carreira salva foi preservada; exporte os dados e recarregue a tela.';protoRender();return;}protoDelta=Object.fromEntries(Object.keys(before).map(k=>[k,protoGame[k]-before[k]]));protoStore();protoRender();document.querySelector('.turn-result')?.scrollIntoView({block:'start',behavior:'instant'});}));document.querySelector('#proto-history')?.addEventListener('click',()=>{protoPage=protoPage==='history'?'play':'history';protoRender();});document.querySelector('#proto-matches')?.addEventListener('click',()=>{protoPage=protoPage==='matches'?'play':'matches';protoRender();});document.querySelector('#proto-export')?.addEventListener('click',()=>protoDownload(JSON.stringify(protoGame,null,2),'1903-brasil-ad-carreira.json'));document.querySelector('#proto-reset')?.addEventListener('click',()=>{if(!confirm('Recomeçar apenas a carreira deste protótipo? Você pode exportá-la antes.'))return;try{localStorage.removeItem(protoKey);protoGame=null;protoRaw=null;protoDelta={};protoError='';protoPage='play';protoRender();}catch{protoError='Não foi possível apagar a carreira. Ela foi preservada.';protoRender();}});}
function protoMatches(){protoRoot.innerHTML=protoShell(`${protoFixedHeader()}<div class="game-body"><h2>Último período</h2>${protoOutcome()}${protoEvidence()}${protoObjective()}${protoShotContext()}${protoLastMatches()}${protoMemories()}</div>${protoFooter()}`);protoBind();}
function protoRender(){if(!protoGame)protoStart();else if(protoPage==='history')protoHistory();else if(protoPage==='matches')protoMatches();else protoPlay();}
protoLoad();protoRender();
