// Separate fictional football simulation. No storage, browser APIs or dependencies.
export const CLUBS=[
 ['sao-luiz','São Luiz',43,20,'#b12c35'],['brasil-pelotas','Brasil de Pelotas',47,28,'#9f2630'],['caxias','Caxias',51,34,'#742d49'],['ypiranga','Ypiranga',54,38,'#467741'],['juventude','Juventude',59,47,'#418652'],['ponte-preta','Ponte Preta',61,49,'#353b45'],['vitoria','Vitória',66,59,'#aa3036'],['vasco','Vasco',71,69,'#343944'],['gremio','Grêmio',75,77,'#3983b3'],['flamengo','Flamengo',79,85,'#b6383c']
].map(([id,name,level,prestige,color])=>({id,name,shortName:name,level,prestige,color}));
export const POSITIONS=[['GK','Goleiro'],['CB','Zagueiro'],['FB','Lateral'],['DM','Volante'],['CM','Meio-campista'],['AM','Meia ofensivo'],['WG','Ponta'],['ST','Atacante']].map(([id,label])=>({id,label}));
const KEYS=['finishing','passing','reading','pace','defending','goalkeeping'];
const WEIGHTS={GK:[0,.1,.25,.05,.1,.5],CB:[.05,.15,.3,.1,.4,0],FB:[.1,.25,.2,.25,.2,0],DM:[.05,.25,.3,.1,.3,0],CM:[.1,.35,.3,.15,.1,0],AM:[.2,.35,.3,.15,0,0],WG:[.3,.2,.2,.3,0,0],ST:[.5,.1,.2,.2,0,0]};
const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,v));
const random=g=>{g.rng=(Math.imul(g.rng,1664525)+1013904223)>>>0;return g.rng/4294967296;};
const roll=(g,p)=>random(g)<clamp(p,0,1);
const integer=(g,min,max)=>min+Math.floor(random(g)*(max-min+1));
const stat=()=>({apps:0,starts:0,minutes:0,goals:0,assists:0,ratingSum:0});
export const club=g=>CLUBS.find(c=>c.id===g.clubId)??null;
export function overall(g){return Math.round(KEYS.reduce((s,k,i)=>s+g.skills[k]*WEIGHTS[g.position][i],0)*(.9+g.proficiency*.001));}
const option=(id,label,hint)=>({id,label,hint});
const num=v=>v.toFixed(1).replace('.',',');
const primary=g=>KEYS[WEIGHTS[g.position].indexOf(Math.max(...WEIGHTS[g.position]))];
function event(g,kind,title,body,choices=[]){g.serial++;g.event={id:`p10v2-${g.serial}`,kind,title,body,choices:choices.map(c=>({...c,id:`${c.id}@${g.serial}`}))};}
function log(g,text){g.log.unshift(text);g.log=g.log.slice(0,100);}
function memory(g,text,change=0,critical=false){const c=club(g);if(!c)return;const m=g.fanMemory[c.id]??={respect:50,entries:[],criticalEntries:[]};m.respect=clamp(m.respect+change);if(critical){m.criticalEntries.unshift(text);m.criticalEntries=m.criticalEntries.slice(0,10);}else{m.entries.unshift(text);m.entries=m.entries.slice(0,4);}}
const labelSkill={finishing:'finalização',passing:'passe',reading:'leitura',pace:'velocidade',defending:'defesa',goalkeeping:'segurança no gol'};
function growth(g,focus,extra=false){
 for(const [i,k]of KEYS.entries()){const role=.55+WEIGHTS[g.position][i]*2;const gain=.34*g.dna.learning*g.dna.aptitudes[k]*role*(focus===k?1.65:1)*(extra?1.7:1)*(.72+g.condition/350)*Math.max(.7,1-g.fatigue/250)*(1-g.skills[k]/120);g.skills[k]=clamp(g.skills[k]+gain,0,99);}
}
const intents=g=>g.position==='GK'?['SAFE','BUILD','SWEEP']:['CB','FB','DM'].includes(g.position)?['HOLD','BUILD','ADVANCE']:g.position==='ST'?['ATTACK','LINK','PRESS']:['CREATE','ATTACK','CONTROL'];
const focusFor=(g,intent)=>({SAFE:'goalkeeping',BUILD:'passing',SWEEP:'reading',HOLD:'defending',ADVANCE:g.position==='FB'?'pace':'defending',ATTACK:'finishing',LINK:'passing',PRESS:'pace',CREATE:'passing',CONTROL:'reading'})[intent]??primary(g);
function formationEvent(g){g.age=[12,14,16][g.formation];g.objective={title:'Aprender sua posição',body:'Três etapas de formação antes do primeiro projeto adulto.',progress:{stages:g.formation},target:{stages:3},progressText:`${g.formation}/3 etapas`,targetText:'3 etapas; escolha onde acumular experiência',status:'ACTIVE'};event(g,'FORMATION',`Seu jogo aos ${g.age}`,`Como ${POSITIONS.find(p=>p.id===g.position).label.toLowerCase()}, você ainda constrói habilidade e experiência. Esta etapa registra aprendizado; o adulto não começa pronto.`,[option('formation:technique','Lapidar a técnica da posição','Melhora as habilidades relevantes para sua função.'),option('formation:reading','Especializar a leitura de jogo','Trabalha leitura/passe e mais experiência na posição.'),option('formation:athletic','Ganhar ritmo e solidez','Trabalha velocidade/defesa e experiência.')]);}
export function createGame(name,position,seed=Date.now()>>>0){
 if(!POSITIONS.some(p=>p.id===position))throw new Error('Posição inválida');
 const g={schema:2,name:String(name||'Jogador').slice(0,60),age:12,position,clubId:null,condition:85,fatigue:10,pressure:15,confidence:60,trust:48,skills:{},proficiency:28,dna:{learning:0,aptitudes:{}},rng:Number(seed)>>>0,seed:Number(seed)>>>0,round:0,season:18,period:0,formation:0,phase:'FORMATION',serial:0,decisions:0,totalstats:stat(),seasonStats:stat(),yearStats:[],playedMatches:[],lastMatches:[],history:[],log:[],fanMemory:{},reputation:0,rival:null,market:[],resolved:[],choicesLog:[],progression:[],objective:null,objectiveHistory:[],lastOutcome:null,roleEvidence:null,recoveryUsed:false,recoveryWork:null,recoveryArc:null,decisiveUsed:false,decisive:null,schedule:[],event:null};
 g.dna.learning=.85+random(g)*.55;for(const k of KEYS){g.dna.aptitudes[k]=.8+random(g)*.55;g.skills[k]=14+random(g)*9;}formationEvent(g);return g;
}
function schedule(g){const rivals=CLUBS.filter(c=>c.id!==g.clubId);let offset=(g.seed+g.season)%9;const last=g.playedMatches.at(-1)?.opponentId;if(rivals[offset].id===last)offset=(offset+1)%9;const first=[...rivals.slice(offset),...rivals.slice(0,offset)].map(c=>c.id);g.schedule=[...first,...first];}
function startSeason(g){g.lastMatches=[];g.roleEvidence=null;g.coachReaction='';g.fanReaction='';g.age=g.season;g.period=0;g.round=0;g.seasonStats=stat();g.phase='PRO';g.condition=clamp(g.condition+8);g.fatigue=clamp(g.fatigue-8);g.pressure=clamp(g.pressure-4);schedule(g);if(g.pendingNewClub){g.pendingNewClub=false;rivalEvent(g);}else if(!g.recoveryUsed&&g.objective?.status==='MISSED')recoveryEvent(g);else planEvent(g);}
function rivalEvent(g){const c=club(g);g.rival={name:['Rafael Nunes','Bruno Medeiros','Caio Fontes'][g.history.length%3],quality:c.level-1};event(g,'RIVALRY','Um projeto, uma disputa por espaço',`${g.rival.name} é um concorrente fictício de nível ${g.rival.quality}. Seu nível é ${overall(g)}. No ${c.name}, a entrada em campo será observada: escolher uma postura não compra a vaga.`,[option('rival:earn','Mostrar meu jogo na função','A próxima meta avaliará sua produção e seus minutos.'),option('rival:team','Construir parceria com o elenco','Estabelece a intenção de cooperar; a contribuição nas partidas decide o efeito.'),option('rival:challenge','Disputar um papel mais ofensivo','Eleva a exigência da próxima meta, sem ganhar titularidade no clique.')]);}
function outputLabel(g){if(g.recoveryWork==='COOPERATE')return 'ações de cooperação';return g.position==='GK'?'defesas':g.position==='ST'?'gols':g.position==='CB'||g.position==='DM'?'intervenções':g.position==='FB'?'ações de criação e intervenção':'chances criadas';}
function objective(g){const strong=overall(g)>=club(g).level+6;const target={apps:strong?4:3,minutes:strong?220:150,good:strong?3:2,output:g.position==='ST'?1:g.position==='GK'?6:['CB','DM'].includes(g.position)?8:g.position==='FB'?10:6};if(g.intentChallenge)target.good++;g.intentChallenge=false;
 if(g.recoveryWork==='COOPERATE')target.output=3;
 return {season:g.season,period:g.period+1,clubId:g.clubId,metric:g.recoveryWork==='COOPERATE'?'cooperation':'role',title:g.recoveryWork?'Provar a mudança de trabalho':'Conquistar confiança pela atuação',body:`O treinador avaliará ${outputLabel(g)} e boas atuações com tempo suficiente, em seis partidas. A ausência de minutos limita a amostra; não vira uma atuação ruim.`,progress:{apps:0,minutes:0,good:0,output:0},target,progressText:`0/${target.apps} participações · 0/${target.minutes} min · 0/${target.good} boas atuações · 0/${target.output} ${outputLabel(g)}`,targetText:`${target.apps} participações, ${target.minutes} min, ${target.good} boas atuações (≥35 min/nota≥7) e ${target.output} ${outputLabel(g)}`,status:'ACTIVE'};}
function planEvent(g){g.objective=objective(g);const opponent=CLUBS.find(c=>c.id===g.schedule[g.round]);const harder=opponent.level>club(g).level+8;const window=g.period+1;const labels={SAFE:['Proteger o gol nas finalizações','Prioriza defesas e leitura; saída curta reduz exposição.'],BUILD:['Iniciar as jogadas com passe','Prioriza passes e criação na saída; erro de construção pode expor o time.'],SWEEP:['Antecipar bolas nas costas','Mais intervenções fora do gol, com risco de exposição.'],HOLD:[harder?'Fechar o setor contra um rival forte':'Ganhar a disputa no meu setor','Prioriza leitura e intervenções; reduz a exposição defensiva.'],ADVANCE:[`Apoiar a construção pela ${g.position==='FB'?'faixa':'recuperação'}`,'Mais chance de criar, com espaço deixado para o rival.'],ATTACK:[g.position==='ST'?`Atacar o espaço contra ${opponent.shortName}`:`Chegar para finalizar neste período`,'Prioriza finalizações e movimentos ofensivos; cobra contribuição no ataque.'],LINK:[`Conectar o ataque para ${window===1?'ganhar':'sustentar'} espaço`,'Prioriza passes e criação; não exige marcar em toda partida.'],PRESS:['Pressionar a saída do adversário','Prioriza intervenções adiantadas e leitura; pede mais energia.'],CREATE:[`Criar oportunidades ${window===2?'entre as linhas':window===3?'no último terço':'para o ataque'}`,'Prioriza passes-chave e chances criadas; gols são uma parte da contribuição.'],CONTROL:[harder?'Controlar o jogo sem se expor':'Dar ritmo ao meio-campo','Prioriza passes e leitura; avalia qualidade das ações, não só gols.']};
 event(g,'PLAN',`${g.season} anos · ${window}º período: ${g.objective.title}`,`Próximo rival: ${opponent.name}, nível ${opponent.level}; ${club(g).name}, nível ${club(g).level}. ${g.objective.targetText}. Recuperação entre jogos é automática; você escolhe uma intenção esportiva para os próximos seis jogos.`,intents(g).map(id=>option(`intent:${id}`,labels[id][0],labels[id][1])));
}
function recoveryEvent(g){g.recoveryUsed=true;g.recoveryArc={clubId:g.clubId,season:g.season,status:'CHOOSING',beforeStarts:(g.lastMatches.length?g.lastMatches:g.playedMatches.filter(m=>m.season===g.season-1).slice(-6)).filter(m=>m.started).length,beforeLevel:overall(g),work:null};event(g,'RECOVERY','Uma resposta para recuperar espaço',`No último período registrado: ${(g.lastMatches.length?g.lastMatches:g.playedMatches.filter(m=>m.season===g.season-1).slice(-6)).filter(m=>m.minutes).length} participações, ${(g.lastMatches.length?g.lastMatches:g.playedMatches.filter(m=>m.season===g.season-1).slice(-6)).filter(m=>m.started).length} titularidades. A meta não foi cumprida ou a oportunidade foi limitada. Escolha uma mudança concreta para ser avaliada no próximo período, sem um bônus automático de vaga.`,[option('recovery:EXTRA',`Trabalhar mais ${labelSkill[primary(g)]}`,'Mais aprendizado da habilidade por seis jogos; esforço cobra condição e fadiga. O retorno depende da atuação.'),option('recovery:READ','Rever as ações e mudar a leitura','Mais aprendizado de leitura por seis jogos; a nova meta precisa de evidência em campo.'),option('recovery:COOPERATE','Apoiar uma função mais simples','Mais aprendizado de passe e exigência orientada à cooperação; não concede minutos imediatamente.')]);}
function decisiveEvent(g){g.decisiveUsed=true;event(g,'DECISIVE','Um teste real para sua nova resposta',`Na próxima participação de ao menos 45 minutos, o treinador observará sua postura. Uma entrada curta não será tratada como prova decisiva. A janela dura até seis jogos.`,[option('decisive:risk','Assumir uma intervenção mais ambiciosa','Aumenta ações e criação, mas expõe o time; reconhecimento depende da atuação suficiente.'),option('decisive:safe','Provar consistência na função','Reduz exposição, priorizando ações corretas; ainda exige desempenho observado.')]);}
function roleOutput(g,m){if(g.objective.metric==='cooperation')return m.chancesCreated+m.assists+m.interventions;return g.position==='GK'?m.saves:g.position==='ST'?m.goals:['CB','DM'].includes(g.position)?m.interventions:g.position==='FB'?m.interventions+m.chancesCreated:m.chancesCreated;}
function updateObjective(g,m){const o=g.objective;if(m.minutes){o.progress.apps++;o.progress.minutes+=m.minutes;o.progress.good+=m.minutes>=35&&m.rating>=7?1:0;o.progress.output+=roleOutput(g,m);}o.progressText=`${o.progress.apps}/${o.target.apps} participações · ${o.progress.minutes}/${o.target.minutes} min · ${o.progress.good}/${o.target.good} boas atuações · ${o.progress.output}/${o.target.output} ${outputLabel(g)}`;}
function assessObjective(g){const o=g.objective;o.status=Object.keys(o.target).every(k=>o.progress[k]>=o.target[k])?'MET':'MISSED';g.objectiveHistory.push(JSON.parse(JSON.stringify(o)));if(o.status==='MET'){const beforeTrust=g.trust,beforeRep=g.reputation;g.trust=clamp(g.trust+3);g.reputation=clamp(g.reputation+2);memory(g,`Cumpriu a meta de ${outputLabel(g)}: ${o.progressText}.`,3,true);g.lastOutcome={title:'Uma meta cumprida em campo',body:`${o.progressText}. O treinador registrou a contribuição: confiança +${num(g.trust-beforeTrust)} e reputação +${num(g.reputation-beforeRep)}. A meta concluída pertence ao ${club(g).name}, aos ${g.season} anos.`};}else{g.lastOutcome={title:o.progress.minutes<o.target.minutes?'Faltou oportunidade para provar a meta':'A meta ainda não foi cumprida',body:`${o.progressText}. ${o.progress.minutes<o.target.minutes?'A amostra limitada não é uma atuação ruim.':'O trabalho precisa de outra resposta esportiva; o tempo sozinho não fecha a meta.'}`};}
 g.lastOutcome.season=g.season;g.lastOutcome.clubId=g.clubId;g.lastOutcome.status=o.status;g.lastOutcome.target={...o.target};g.lastOutcome.achieved={...o.progress};
 if(g.recoveryWork){const met=o.status==='MET';g.recoveryArc.status=met?'PROVED':'UNPROVED';g.recoveryArc.afterStarts=g.lastMatches.filter(m=>m.started).length;g.recoveryArc.afterLevel=overall(g);memory(g,`Resposta ${g.recoveryWork}: ${met?'mudança comprovada pela meta':'mudança ainda sem comprovação'}; ${o.progressText}.`,met?2:0,true);g.recoveryWork=null;}
}
function simulate(g,intent){
 const c=club(g),opponent=CLUBS.find(c=>c.id===g.schedule[g.round]);
 // Normal recovery is part of the calendar, not an action the player must spam.
 g.condition=clamp(g.condition+5);g.fatigue=clamp(g.fatigue-4.5);g.pressure+=((opponent.level>c.level+10?25:20)-g.pressure)*.08;
 const extra=g.recoveryWork==='EXTRA';if(extra){g.condition=clamp(g.condition-3);g.fatigue=clamp(g.fatigue+3);}
 const role=overall(g),effective=role-Math.max(0,80-g.condition)*.08-Math.max(0,g.fatigue-35)*.05-Math.max(0,g.pressure-60)*.04;
 const recent=g.playedMatches.filter(m=>m.clubId===c.id&&m.minutes>=35).slice(-6),form=recent.length?recent.reduce((s,m)=>s+m.rating,0)/recent.length:6.7;
 const starterChance=clamp(.55+(effective-g.rival.quality)*.025+(g.trust-50)*.004+(form-6.7)*.06,.12,.89);
 const started=roll(g,starterChance),minutes=started?integer(g,66,90):roll(g,.82)?integer(g,14,34):0,share=minutes/90;
 let posture=null;if(g.decisive){g.decisive.remaining--;if(minutes>=45){posture=g.decisive.kind;g.decisive=null;}else if(g.decisive.remaining===0){memory(g,'A janela especial acabou sem participação de 45 minutos; nenhuma prova decisiva foi atribuída.',0,true);g.decisive=null;}}
 const m={season:g.season,round:g.round+1,clubId:c.id,opponent:opponent.name,opponentId:opponent.id,gf:0,ga:0,minutes,started,goals:0,assists:0,rating:0,saves:0,result:'D',coach:'',fans:'',moment:'',strategy:intent,teamChances:0,oppChances:0,shots:0,shotsOnTarget:0,chancesCreated:0,keyPasses:0,passAttempts:0,completedPasses:0,interventions:0,failedInterventions:0,good:false};
 const attacker=['ST','WG','AM'].includes(g.position),defender=['CB','FB','DM'].includes(g.position),creator=['CM','AM','WG','FB','DM'].includes(g.position);
 for(let possession=0;possession<9;possession++){
  const involved=minutes>0&&roll(g,share*(creator?.64:g.position==='ST'?.48:.28)*(g.arrivalIntent==='team'&&g.period===0?1.1:1));let passCreated=false;
  if(involved){const completedBefore=m.completedPasses;const attempts=creator?integer(g,1,3):1;for(let i=0;i<attempts;i++){m.passAttempts++;if(roll(g,clamp(.6+(g.skills.passing-opponent.level)*.005+(intent==='CONTROL'||intent==='BUILD'?.09:0),.38,.88)))m.completedPasses++;}
   if(roll(g,clamp(.33+(g.skills.reading+g.skills.passing-opponent.level*2)*.004+(['CREATE','LINK','BUILD'].includes(intent)?.13:0),.13,.76)))passCreated=m.completedPasses>completedBefore;
  }
  const creation=clamp(.40+(c.level-opponent.level)*.004+(passCreated?.25:0)+(posture==='risk'?.07:0)+(['ATTACK','ADVANCE'].includes(intent)?.025*share:0),.14,.78);
  if(roll(g,creation)){
   m.teamChances++;if(passCreated){m.chancesCreated++;m.keyPasses++;}
   const personalShot=minutes>0&&g.position!=='GK'&&roll(g,share*(g.position==='ST'?.65:g.position==='WG'?.4:g.position==='AM'?.25:g.position==='CM'?.12:.035)*(intent==='ATTACK'?1.3:intent==='CREATE'||intent==='CONTROL'?.65:1));
   let goal=false;if(personalShot){m.shots++;const onTarget=roll(g,clamp(.44+(g.skills.finishing-opponent.level)*.005,.26,.76));if(onTarget){m.shotsOnTarget++;goal=roll(g,clamp(.4+(g.skills.finishing-opponent.level)*.005,.2,.68));}if(goal)m.goals++;}
   else{goal=roll(g,clamp(.30+(c.level-opponent.level)*.003,.15,.5));if(goal&&passCreated)m.assists++;}
   if(goal)m.gf++;
  }
  let intervention=false;
  if(minutes>0&&g.position!=='GK'&&roll(g,share*(defender?.6:g.position==='CM'?.32:.17))){if(roll(g,clamp(.52+(g.skills.defending+g.skills.reading-opponent.level*2)*.004+(['HOLD','PRESS'].includes(intent)?.09:0),.24,.84))){m.interventions++;intervention=true;}else m.failedInterventions++;}
  const oppCreation=clamp(.42+(opponent.level-c.level)*.004-(intervention?.22:0)+(posture==='risk'?.06:posture==='safe'?-.05:0)+(intent==='ADVANCE'?.04*share:intent==='HOLD'?-.03*share:0),.14,.78);
  if(roll(g,oppCreation)){
   m.oppChances++;const onTarget=roll(g,.68);if(onTarget){const keeper=g.position==='GK'&&minutes>0&&roll(g,share),keeperLevel=keeper?g.skills.goalkeeping:c.level;const goal=roll(g,clamp(.4+(opponent.level-keeperLevel)*.005,.18,.68));if(goal)m.ga++;else if(keeper)m.saves++;}
  }
 }
 if(minutes>0){
  let rating=6.45+(effective-c.level)*.01;
  if(g.position==='GK')rating+=m.saves*.25+(m.ga===0&&minutes>=45?.35:0)-Math.max(0,m.ga-2)*.13;
  else if(defender)rating+=m.interventions*.24+m.chancesCreated*.18+m.completedPasses*.025+m.assists*.55+m.goals*.85-m.failedInterventions*.1;
  else if(g.position==='ST')rating+=m.goals*1.2+m.assists*.55+m.shotsOnTarget*.13+m.chancesCreated*.13-m.shots*.035;
  else rating+=m.goals*.9+m.assists*.62+m.chancesCreated*.26+m.completedPasses*.035+m.interventions*.1-(m.passAttempts-m.completedPasses)*.07;
  // Short appearances are partial evidence, never judged as a whole match failure.
  if(minutes<35)rating=6.5+(rating-6.5)*.7;
  m.rating=Math.round(clamp(rating,4.5,9.5)*10)/10;m.good=minutes>=35&&m.rating>=7;
 }
 m.result=m.gf>m.ga?'W':m.gf<m.ga?'L':'D';
 if(minutes>=35&&g.arrivalIntent==='team'&&g.period===0&&m.completedPasses>=4)g.trust=clamp(g.trust+.2);
 if(minutes>=35){g.trust=clamp(g.trust+(m.rating>=7?.7:m.rating<6.3?-.65:0));const target=clamp(65+(m.rating-6.7)*14,35,88);g.confidence+= (target-g.confidence)*.12;g.reputation=clamp(g.reputation+(m.good?.55:0)+m.goals*.3+m.assists*.2,0,100);}
 // Expected defeats against stronger teams do not blame a bench player or erase his evidence.
 if(m.result==='L'&&c.level>=opponent.level&&minutes>=45&&m.rating<6.3)g.pressure=clamp(g.pressure+2);else if(m.good)g.pressure=clamp(g.pressure-1);
 if(posture){const success=m.good;g.trust=clamp(g.trust+(success?2:minutes>=45&&m.rating<6.3?-2:0));g.reputation=clamp(g.reputation+(success?1.5:0));m.moment=`Postura ${posture==='risk'?'ambiciosa':'segura'} observada por ${minutes} minutos: ${success?'contribuição consistente reconhecida':'a meta ainda precisa de evidência'}.`;memory(g,m.moment,success?2:0,true);}
 const roleText=g.position==='GK'?`${m.saves} defesas observadas`:defender?`${m.interventions} intervenções e ${m.chancesCreated} chances criadas`:g.position==='ST'?`${m.shots} finalizações, ${m.goals} gols e ${m.assists} assistências`:`${m.completedPasses}/${m.passAttempts} passes de construção e ${m.chancesCreated} chances criadas`;
 if(!minutes){m.coach=`Sem minutos contra ${opponent.name}: não houve uma atuação sua para avaliar; a disputa continua.`;m.fans=`${c.name} ${m.gf}–${m.ga} ${opponent.name}: a torcida viu o time, não uma atuação do jogador.`;}
 else if(minutes<35){m.coach=`Entrada de ${minutes} minutos contra ${opponent.name}: ${roleText}. Evidência parcial, sem julgamento de uma partida inteira.`;m.fans=`Em ${minutes} minutos: ${m.goals}G/${m.assists}A e ${roleText}; a oportunidade foi curta.`;}
 else{m.coach=`Contra ${opponent.name}: ${roleText}, nota ${num(m.rating)}. ${m.good?'Contribuição positiva para a disputa por espaço.':m.rating<6.3?'A execução da função precisa melhorar.':'Atuação registrada; ainda falta consistência para a meta.'}`;m.fans=`${c.name} ${m.gf}–${m.ga} ${opponent.name}. ${m.good?'A torcida reconheceu':'A torcida observou'} ${roleText}${opponent.level>c.level+10?'; o rival era mais forte nesta simulação':''}.`;}
 memory(g,`${opponent.name}: ${minutes} min, ${roleText}.`,m.good?1:minutes>=45&&m.rating<6.3?-1:0);
 for(const s of [g.seasonStats,g.totalstats])if(minutes){s.apps++;s.starts+=started?1:0;s.minutes+=minutes;s.goals+=m.goals;s.assists+=m.assists;s.ratingSum+=m.rating;}
 g.round++;g.playedMatches.push(m);g.condition=clamp(g.condition-(minutes>=45?4:minutes?2:1));g.fatigue=clamp(g.fatigue+(minutes>=45?2.5:minutes?1.5:1));
 const training=g.recoveryWork==='READ'?'reading':g.recoveryWork==='COOPERATE'?'passing':extra?primary(g):focusFor(g,intent);growth(g,training,extra);g.proficiency=clamp(g.proficiency+(minutes>=45?.65:minutes?.28:.12),0,100);updateObjective(g,m);return m;
}
function playPeriod(g,intent){const beforeOverall=overall(g),skills={...g.skills},proficiency=g.proficiency;g.lastMatches=[];for(let i=0;i<6;i++)g.lastMatches.push(simulate(g,intent));g.period++;g.progression.push({season:g.season,period:g.period,beforeOverall,afterOverall:overall(g),skillChanges:Object.fromEntries(KEYS.map(k=>[k,Number((g.skills[k]-skills[k]).toFixed(3))])),experienceGain:Number((g.proficiency-proficiency).toFixed(3)),intent});
 const part=g.lastMatches.filter(m=>m.minutes>0);g.roleEvidence={minutes:part.reduce((s,m)=>s+m.minutes,0),goals:part.reduce((s,m)=>s+m.goals,0),assists:part.reduce((s,m)=>s+m.assists,0),chancesCreated:part.reduce((s,m)=>s+m.chancesCreated,0),keyPasses:part.reduce((s,m)=>s+m.keyPasses,0),completedPasses:part.reduce((s,m)=>s+m.completedPasses,0),interventions:part.reduce((s,m)=>s+m.interventions,0),saves:part.reduce((s,m)=>s+m.saves,0),good:part.filter(m=>m.good).length,description:`${part.length} participações, ${g.lastMatches.filter(m=>m.started).length} titularidades; evidência da função acumulada em seis jogos.`};
 assessObjective(g);g.coachReaction=`${g.roleEvidence.description} ${g.lastOutcome.body}`;g.fanReaction=g.lastMatches.at(-1).fans;log(g,`${club(g).name}: intenção ${intent}, OVR ${beforeOverall}→${overall(g)}, ${g.roleEvidence.description}`);nextPeriod(g);
}
function marketEvent(g){const c=club(g),matches=g.playedMatches.filter(m=>m.season===g.season&&m.minutes>0),rating=g.seasonStats.apps?g.seasonStats.ratingSum/g.seasonStats.apps:0,good=matches.filter(m=>m.good).length,score=overall(g)+Math.min(8,g.reputation*.18);const proof=g.seasonStats.minutes>=200&&(good>=2||rating>=6.8);let pool=CLUBS.filter(x=>x.id!==c.id&&x.level<=score+10&&x.level>=c.level-10).sort((a,b)=>a.level-b.level);g.market=[];g.marketModes={};
 if(proof&&pool.length){const stable=pool.filter(x=>x.level<=c.level+4).at(-1)??pool[0],higher=pool.filter(x=>x.level>c.level+4).at(-1);g.market.push(stable.id);if(higher&&higher.id!==stable.id)g.market.push(higher.id);if(good>=6&&pool.length>2){const middle=pool[Math.floor(pool.length/2)];if(!g.market.includes(middle.id))g.market.push(middle.id);}for(const id of g.market)g.marketModes[id]='OFFER';}
 else if(g.seasonStats.minutes>=100&&overall(g)>=38){pool=CLUBS.filter(x=>x.id!==c.id&&x.level<=Math.max(48,overall(g)+5)&&x.level<=c.level+5);if(pool.length){g.market=[pool[0].id];g.marketModes[pool[0].id]='ASSESSMENT';}}
 const evidence=`${g.seasonStats.apps} participações, ${g.seasonStats.minutes} minutos, ${good} boas atuações e nota ${num(rating)}; ${g.position==='ST'?g.seasonStats.goals+' gols':g.position==='GK'?matches.reduce((s,m)=>s+m.saves,0)+' defesas':matches.reduce((s,m)=>s+m.chancesCreated+m.interventions,0)+' ações de criação/intervenção'}.`;
 event(g,'INTEREST','O que sua temporada fez aparecer',g.market.length?`${evidence} ${g.market.map(id=>CLUBS.find(c=>c.id===id).name).join(' e ')} ${proof?'abriram interesse por um projeto':'oferecem uma avaliação, sem contrato garantido'}. Mais exigência pode significar menos minutos.`:`${evidence} Não surgiu novo contato neste ano; continuar e mudar a resposta esportiva permanece possível.`,[...g.market.map(id=>option(`contact:${id}`,`${g.marketModes[id]==='ASSESSMENT'?'Ouvir uma avaliação no':'Conversar com'} ${CLUBS.find(c=>c.id===id).name}`,g.marketModes[id]==='ASSESSMENT'?'Pode recuperar uma rota em um projeto modesto; aprovação não é certa.':'O interesse precisa virar contato e proposta antes de mudar clube.')),option('market:stay',`Continuar no ${c.name}`,'Mantém o projeto; a temporada encerrada fica preservada.')]);
}
function endSeason(g){g.yearStats.push({age:g.season,season:g.season,clubId:g.clubId,...g.seasonStats});log(g,`${g.season} anos: ${g.seasonStats.apps} participações, ${g.seasonStats.starts} titularidades, OVR ${overall(g)}.`);if(g.season===20){g.age=21;g.phase='DONE';event(g,'DONE','Uma trajetória até os 21',`O recorte termina, não sua carreira. ${g.totalstats.apps} participações, ${g.totalstats.starts} titularidades e ${g.totalstats.minutes} minutos. Seu trabalho e suas metas ficam nos registros abaixo.`);return;}marketEvent(g);}
function finishMarket(g){g.season++;startSeason(g);}
function nextPeriod(g){if(g.period===3){endSeason(g);return;}if(!g.recoveryUsed&&(g.objective.status==='MISSED'||g.lastMatches.filter(m=>m.started).length<3)){recoveryEvent(g);return;}if(g.season===19&&g.period===1&&!g.decisiveUsed){decisiveEvent(g);return;}planEvent(g);}
function validAction(g,id){const base=id.split('@')[0],kind=g.event?.kind;
 if(kind==='FORMATION')return ['formation:technique','formation:reading','formation:athletic'].includes(base);
 if(kind==='RIVALRY')return ['rival:earn','rival:team','rival:challenge'].includes(base);
 if(kind==='PLAN')return intents(g).some(x=>base===`intent:${x}`);
 if(kind==='RECOVERY')return ['recovery:EXTRA','recovery:READ','recovery:COOPERATE'].includes(base);
 if(kind==='DECISIVE')return ['decisive:risk','decisive:safe'].includes(base);
 if(kind==='INTEREST')return base==='market:stay'||g.market?.some(c=>base===`contact:${c}`&&CLUBS.some(x=>x.id===c));
 if(kind==='CONTACT')return base==='market:stay'||base===`offer:${g.contactClub}`&&CLUBS.some(c=>c.id===g.contactClub);
 if(kind==='OFFER')return base==='market:stay'||base===`accept:${g.offer?.clubId}`&&CLUBS.some(c=>c.id===g.offer?.clubId);
 if(kind==='ASSESSMENT_RESULT')return base==='market:stay';return false;
}
/** Exact serial choice preflight, before even recording the decision. */
export function choose(g,id){
 if(!validGame(g)||g.schema!==2||g.phase==='DONE'||typeof id!=='string'||!g.event?.choices.some(c=>c.id===id)||g.resolved.includes(g.event.id)||!validAction(g,id))return false;
 const kind=g.event.kind,key=g.event.id,selected=g.event.choices.find(c=>c.id===id);g.choicesLog.push({eventId:key,kind,id,label:selected.label,age:g.age,clubId:g.clubId,round:g.round});g.resolved.push(key);g.decisions++;id=id.split('@')[0];
 if(kind==='FORMATION'){const before=overall(g),mode=id.split(':')[1],skills={...g.skills};for(const k of KEYS){const priority=mode==='technique'?WEIGHTS[g.position][KEYS.indexOf(k)]>=.25:mode==='reading'?['reading','passing'].includes(k):['pace','defending'].includes(k);g.skills[k]=clamp(g.skills[k]+(priority?15:6)*g.dna.learning*g.dna.aptitudes[k],0,99);}const experience=mode==='reading'?15:8;g.proficiency=clamp(g.proficiency+experience);g.progression.push({season:g.age,period:0,beforeOverall:before,afterOverall:overall(g),skillChanges:Object.fromEntries(KEYS.map(k=>[k,Number((g.skills[k]-skills[k]).toFixed(3))])),experienceGain:experience,intent:mode});g.lastOutcome={title:'Aprendizado registrado',body:`Etapa dos ${g.age} anos: ${labelSkill[primary(g)]}: ${num(skills[primary(g)])}→${num(g.skills[primary(g)])}; experiência +${experience}.`};g.formation++;if(g.formation<3)formationEvent(g);else{g.objective.progress.stages=3;g.objective.progressText='3/3 etapas concluídas';g.objective.targetText='Formação concluída; a próxima meta pertence ao projeto adulto';g.objective.status='MET';g.lastOutcome.season=g.age;g.lastOutcome.clubId=null;g.age=18;g.phase='PRO';g.clubId=CLUBS[overall(g)>=62?2:overall(g)>=55?1:0].id;g.history.push({age:18,clubId:g.clubId,reason:'Primeiro projeto após formação'});schedule(g);rivalEvent(g);}return true;}
 if(kind==='RIVALRY'){g.arrivalIntent=id.slice(6);g.intentChallenge=id==='rival:challenge';memory(g,`Chegada: ${selected.label}. A decisão será avaliada nas partidas.`,0,true);planEvent(g);return true;}
 if(kind==='PLAN'){playPeriod(g,id.slice(7));return true;}
 if(kind==='RECOVERY'){g.recoveryWork=id.slice(9);g.recoveryArc.work=g.recoveryWork;g.recoveryArc.status='WORKING';memory(g,`Mudou o trabalho: ${selected.label}; prova nos próximos seis jogos.`,0,true);planEvent(g);return true;}
 if(kind==='DECISIVE'){g.decisive={kind:id.endsWith('risk')?'risk':'safe',remaining:6};planEvent(g);return true;}
 if(kind==='INTEREST'){if(id==='market:stay'){finishMarket(g);return true;}g.contactClub=id.slice(8);const c=CLUBS.find(c=>c.id===g.contactClub),assessment=g.marketModes[c.id]==='ASSESSMENT';event(g,'CONTACT',`${assessment?'Avaliação':'Contato'} no ${c.name}`,`Projeto de nível ${c.level}, seu OVR ${overall(g)}. ${assessment?'O clube avaliará sua experiência e evidência recente; pode não oferecer contrato.':'A evidência da temporada abriu uma negociação; o espaço será disputado.'}`,[option(`offer:${c.id}`,assessment?'Participar da avaliação':'Pedir a proposta concreta',assessment?'A resposta depende da qualidade e da amostra; nenhuma habilidade cresce pelo aceite.':'Conhece salário e exigência antes de decidir.'),option('market:stay','Encerrar contato e permanecer','Não apaga as atuações nem a meta anterior.')]);return true;}
 if(kind==='CONTACT'){if(id==='market:stay'){finishMarket(g);return true;}const c=CLUBS.find(c=>c.id===g.contactClub);if(g.marketModes[c.id]==='ASSESSMENT'){const rating=g.seasonStats.apps?g.seasonStats.ratingSum/g.seasonStats.apps:6.5,probability=clamp(.45+(overall(g)-c.level)*.02+(rating-6.5)*.12,.2,.8);if(!roll(g,probability)){g.lastOutcome={title:'A avaliação não virou contrato',body:`${c.name} não abriu proposta após esta avaliação. A experiência e os números do ano continuam registrados.`};event(g,'ASSESSMENT_RESULT','Uma tentativa sem proposta',g.lastOutcome.body,[option('market:stay',`Retomar o ${club(g).name}`,'Muda a resposta em campo na próxima temporada; a rota não está encerrada.')]);return true;}}
  g.offer={clubId:c.id,monthly:Math.round((1500+c.prestige*180+Math.max(0,overall(g)-45)*500)/50)*50};event(g,'OFFER',`Proposta do ${c.name}`,`Salário ficcional R$ ${g.offer.monthly.toLocaleString('pt-BR')} por mês. Projeto de nível ${c.level}; experiência e confiança no novo clube ainda terão que virar minutos.`,[option(`accept:${c.id}`,`Aceitar o ${c.name}`,'Muda de projeto; confiança inicia em48 e a exigência do concorrente acompanha o nível do clube.'),option('market:stay',`Continuar no ${club(g).name}`,'Preserva o espaço construído; não aceita o salário do outro projeto.')]);return true;}
 if(kind==='OFFER'){if(id.startsWith('accept:')){g.clubId=g.offer.clubId;g.salary=g.offer.monthly;g.trust=48;const m=g.fanMemory[g.clubId];if(m){g.pressure=clamp(g.pressure+(50-m.respect)*.1);g.trust=clamp(g.trust+(m.respect-50)*.08);}g.history.push({age:g.season+1,clubId:g.clubId,reason:'Proposta aceita após contato'});g.pendingNewClub=true;log(g,`Aceitou ${club(g).name}; disputa de espaço reabre com exigência maior.`);}delete g.offer;finishMarket(g);return true;}
 if(kind==='ASSESSMENT_RESULT'){finishMarket(g);return true;}return false;
}
/** Validate hydration without changing supplied state. Schema1 is deliberately not migrated. */
export function validGame(g){
 const bound=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;
 const finite=(v,ancestors=new Set())=>{if(typeof v==='number')return Number.isFinite(v);if(!v||typeof v!=='object')return true;if(ancestors.has(v))return false;ancestors.add(v);const ok=Object.values(v).every(x=>finite(x,ancestors));ancestors.delete(v);return ok;};
 const stats=s=>s&&['apps','starts','minutes','goals','assists','ratingSum'].every(k=>bound(s[k],0,1e6))&&s.starts<=s.apps;
 try{if(!g||g.schema!==2||typeof g.name!=='string'||g.name.length>60||!POSITIONS.some(p=>p.id===g.position)||g.clubId!==null&&!CLUBS.some(c=>c.id===g.clubId)||!bound(g.age,12,21)||!['FORMATION','PRO','DONE'].includes(g.phase))return false;
 if(!['condition','fatigue','pressure','confidence','trust','proficiency','reputation'].every(k=>bound(g[k],0,100))||!KEYS.every(k=>bound(g.skills?.[k],0,99))||!bound(g.rng,0,4294967295)||!Number.isInteger(g.rng)||!bound(g.dna?.learning,.5,2)||!KEYS.every(k=>bound(g.dna?.aptitudes?.[k],.5,2)))return false;
 if(![['serial',1,40],['decisions',0,25],['formation',0,3],['period',0,3],['round',0,18],['season',18,20]].every(([k,a,b])=>Number.isInteger(g[k])&&bound(g[k],a,b)))return false;
 if(!stats(g.totalstats)||!stats(g.seasonStats)||!Array.isArray(g.yearStats)||g.yearStats.length>3||!g.yearStats.every(stats)||!Array.isArray(g.playedMatches)||g.playedMatches.length>54||!Array.isArray(g.lastMatches)||g.lastMatches.length>6)return false;
 for(const m of g.playedMatches)if(!CLUBS.some(c=>c.id===m.clubId)||!CLUBS.some(c=>c.id===m.opponentId)||!bound(m.gf,0,m.teamChances)||!bound(m.ga,0,m.oppChances)||!bound(m.teamChances,0,9)||!bound(m.oppChances,0,9)||!bound(m.minutes,0,90)||!bound(m.rating,0,10)||!bound(m.goals,0,m.gf)||!bound(m.assists,0,m.gf-m.goals)||m.completedPasses>m.passAttempts||typeof m.started!=='boolean'||typeof m.coach!=='string'||typeof m.fans!=='string'||m.minutes===0&&(m.rating||m.goals||m.assists||m.saves||m.completedPasses||m.interventions||m.chancesCreated))return false;
 if(!Array.isArray(g.choicesLog)||g.choicesLog.length!==g.decisions||!Array.isArray(g.progression)||!Array.isArray(g.objectiveHistory)||!Array.isArray(g.history)||!Array.isArray(g.resolved)||!Array.isArray(g.log)||!g.fanMemory||!g.event||typeof g.event.id!=='string'||typeof g.event.title!=='string'||typeof g.event.body!=='string'||!Array.isArray(g.event.choices)||g.event.choices.length>4)return false;
 if(g.serial!==g.decisions+1||g.event.id!==`p10v2-${g.serial}`||g.resolved.length!==g.decisions||new Set(g.resolved).size!==g.resolved.length||!g.choicesLog.every((c,i)=>c.eventId===g.resolved[i]&&typeof c.label==='string'&&typeof c.id==='string'))return false;
 const sum=matches=>matches.reduce((s,m)=>{if(m.minutes){s.apps++;s.starts+=m.started?1:0;s.minutes+=m.minutes;s.goals+=m.goals;s.assists+=m.assists;s.ratingSum+=m.rating;}return s;},{apps:0,starts:0,minutes:0,goals:0,assists:0,ratingSum:0});
 const equal=(a,b)=>Object.keys(b).every(k=>Math.abs(a[k]-b[k])<1e-8);
 if(!equal(g.totalstats,sum(g.playedMatches))||!equal(g.seasonStats,sum(g.playedMatches.filter(m=>m.season===g.season)))||!g.yearStats.every(s=>equal(s,sum(g.playedMatches.filter(m=>m.season===s.season))))||new Set(g.yearStats.map(s=>s.season)).size!==g.yearStats.length)return false;
 if(g.phase!=='FORMATION'&&(g.schedule.length!==18||new Set(g.schedule).size!==9||g.schedule.some(id=>id===g.clubId||!CLUBS.some(c=>c.id===id))||g.schedule.some((id,i)=>i>0&&id===g.schedule[i-1])||[...new Set(g.schedule)].some(id=>g.schedule.filter(x=>x===id).length!==2)))return false;
 if(!g.event.choices.every(c=>typeof c.id==='string'&&c.id.endsWith(`@${g.serial}`)&&validAction(g,c.id)&&typeof c.label==='string'&&typeof c.hint==='string')||new Set(g.event.choices.map(c=>c.id)).size!==g.event.choices.length)return false;
 if(g.phase==='DONE'&&(g.age!==21||g.event.kind!=='DONE'||g.event.choices.length))return false;if(g.phase!=='DONE'&&!g.event.choices.length)return false;
 if(g.objective&&(!['ACTIVE','MET','MISSED'].includes(g.objective.status)||typeof g.objective.progressText!=='string'||typeof g.objective.targetText!=='string'))return false;
 const objectiveContext=o=>Number.isInteger(o.season)&&bound(o.season,18,20)&&Number.isInteger(o.period)&&bound(o.period,1,3)&&CLUBS.some(c=>c.id===o.clubId)&&['role','cooperation'].includes(o.metric);
 if(g.objective?.metric&&!objectiveContext(g.objective)||g.objectiveHistory.length>9||!g.objectiveHistory.every(o=>objectiveContext(o)&&['MET','MISSED'].includes(o.status)&&typeof o.progressText==='string'&&typeof o.targetText==='string'&&g.playedMatches.some(m=>m.season===o.season&&m.clubId===o.clubId))||new Set(g.objectiveHistory.map(o=>`${o.season}:${o.period}`)).size!==g.objectiveHistory.length)return false;
 // Hydrated dependencies must be safe before choose records any mutation.
 const knownClub=id=>CLUBS.some(c=>c.id===id),integer=(v,a,b)=>Number.isInteger(v)&&bound(v,a,b);
 const text=v=>typeof v==='string';
 if(g.progression.length>12||!g.progression.every(p=>p&&integer(p.season,12,20)&&integer(p.period,0,3)&&bound(p.beforeOverall,0,99)&&bound(p.afterOverall,0,99)&&bound(p.experienceGain,0,100)&&text(p.intent)&&p.skillChanges&&KEYS.every(k=>bound(p.skillChanges[k],0,99))))return false;
 if(g.history.length>3||!g.history.every(h=>h&&integer(h.age,18,20)&&knownClub(h.clubId)&&text(h.reason))||g.log.length>100||!g.log.every(text))return false;
 if(!g.yearStats.every(h=>h&&integer(h.age,18,20)&&h.season===h.age&&knownClub(h.clubId))||!g.choicesLog.every(c=>c&&text(c.kind)&&integer(c.age,12,20)&&(c.clubId===null||knownClub(c.clubId))&&integer(c.round,0,18)))return false;
 if(!Array.isArray(g.market)||g.market.length>3||new Set(g.market).size!==g.market.length||!g.market.every(knownClub)||!Array.isArray(g.schedule)||g.schedule.length>18||!g.schedule.every(knownClub))return false;
 if(g.lastOutcome!==null&&(!g.lastOutcome||!text(g.lastOutcome.title)||!text(g.lastOutcome.body)))return false;
 if(!g.objective||!text(g.objective.title)||!text(g.objective.body)||!g.objectiveHistory.every(o=>o&&text(o.title)&&text(o.body)))return false;
 const validMatch=m=>m&&integer(m.season,18,20)&&integer(m.round,1,18)&&knownClub(m.clubId)&&knownClub(m.opponentId)&&text(m.opponent)&&text(m.result)&&text(m.strategy)&&text(m.moment)&&typeof m.good==='boolean'&&['gf','ga','minutes','goals','assists','saves','shots','shotsOnTarget','chancesCreated','keyPasses','passAttempts','completedPasses','interventions','failedInterventions','teamChances','oppChances'].every(k=>integer(m[k],0,k==='minutes'?90:100))&&m.shotsOnTarget<=m.shots&&m.goals<=m.shotsOnTarget&&m.completedPasses<=m.passAttempts;
 if(!g.playedMatches.every(validMatch)||!g.lastMatches.every(m=>validMatch(m)&&g.playedMatches.some(a=>a.season===m.season&&a.round===m.round&&JSON.stringify(a)===JSON.stringify(m))))return false;
 if(g.phase!=='FORMATION'&&(!knownClub(g.clubId)||!g.rival||typeof g.rival.name!=='string'||!bound(g.rival.quality,0,100)))return false;
 if(typeof g.recoveryUsed!=='boolean'||typeof g.decisiveUsed!=='boolean'||g.recoveryWork!==null&&!['EXTRA','READ','COOPERATE'].includes(g.recoveryWork))return false;
 if(g.recoveryArc!==null){const a=g.recoveryArc;if(!a||!knownClub(a.clubId)||!integer(a.season,18,20)||!['CHOOSING','WORKING','PROVED','UNPROVED'].includes(a.status)||!integer(a.beforeStarts,0,6)||!bound(a.beforeLevel,0,99)||a.work!==null&&!['EXTRA','READ','COOPERATE'].includes(a.work))return false;}
 if(g.event.kind==='RECOVERY'&&(!g.recoveryUsed||!g.recoveryArc||g.recoveryArc.status!=='CHOOSING'||g.recoveryArc.clubId!==g.clubId||g.recoveryArc.season!==g.season)||g.recoveryWork&&(!g.recoveryArc||g.recoveryArc.status!=='WORKING'||g.recoveryArc.work!==g.recoveryWork))return false;
 if(Array.isArray(g.fanMemory)||!Object.entries(g.fanMemory).every(([id,m])=>knownClub(id)&&m&&bound(m.respect,0,100)&&Array.isArray(m.entries)&&m.entries.length<=4&&m.entries.every(x=>typeof x==='string')&&Array.isArray(m.criticalEntries)&&m.criticalEntries.length<=10&&m.criticalEntries.every(x=>typeof x==='string')))return false;
 if(g.roleEvidence!==null){const r=g.roleEvidence,keys=['minutes','goals','assists','chancesCreated','keyPasses','completedPasses','interventions','saves','good'];if(!r||typeof r.description!=='string'||!keys.every(k=>integer(r[k],0,k==='minutes'?540:1000)))return false;for(const k of keys){const observed=g.lastMatches.reduce((v,m)=>v+(k==='good'?(m.good?1:0):m[k]),0);if(r[k]!==observed)return false;}}
 const validObjective=o=>{if(!objectiveContext(o)||!o.target||!o.progress)return false;const t=o.target,q=o.progress;const output=o.metric==='cooperation'?3:g.position==='ST'?1:g.position==='GK'?6:['CB','DM'].includes(g.position)?8:g.position==='FB'?10:6;
 if(!((t.apps===3&&t.minutes===150)||(t.apps===4&&t.minutes===220))||![t.apps-1,t.apps].includes(t.good)||t.output!==output||!integer(q.apps,0,6)||!integer(q.minutes,0,540)||!integer(q.good,0,q.apps)||!integer(q.output,0,1000))return false;
 const matches=g.playedMatches.filter(m=>m.season===o.season&&m.clubId===o.clubId&&m.round>(o.period-1)*6&&m.round<=o.period*6),actual={apps:0,minutes:0,good:0,output:0};for(const m of matches)if(m.minutes){actual.apps++;actual.minutes+=m.minutes;actual.good+=m.minutes>=35&&m.rating>=7?1:0;actual.output+=o.metric==='cooperation'?m.chancesCreated+m.assists+m.interventions:g.position==='ST'?m.goals:g.position==='GK'?m.saves:['CB','DM'].includes(g.position)?m.interventions:g.position==='FB'?m.interventions+m.chancesCreated:m.chancesCreated;}
 if(!equal(q,actual))return false;const met=Object.keys(t).every(k=>q[k]>=t[k]);return o.status==='ACTIVE'?matches.length===0:o.status===(met?'MET':'MISSED')&&matches.length===6;};
 if(!g.objective||g.objective.metric&&!validObjective(g.objective)||!g.objectiveHistory.every(validObjective))return false;
 if(g.event.kind==='PLAN'&&(!g.objective.metric||g.objective.status!=='ACTIVE'||g.objective.clubId!==g.clubId||g.objective.season!==g.season||g.objective.period!==g.period+1))return false;
 if(['CONTACT','OFFER'].includes(g.event.kind)&&(!knownClub(g.contactClub)||!g.market.includes(g.contactClub)||!g.marketModes||!['OFFER','ASSESSMENT'].includes(g.marketModes[g.contactClub])))return false;
 if(g.event.kind==='OFFER'&&(!g.offer||g.offer.clubId!==g.contactClub||!bound(g.offer.monthly,1,1e7)))return false;
 return finite(g);}catch{return false;}
}
