import assert from 'node:assert/strict';
import {CLUBS,POSITIONS,createGame,choose,overall,club,validGame} from './engine.mjs';
const pick=(g,prefix)=>g.event.choices.find(c=>c.id.startsWith(`${prefix}@`));
function policy(g,{formation=[0,1,2],market='stay',style=0,recovery='EXTRA'}={}){
 const e=g.event;if(e.kind==='FORMATION')return e.choices[formation[g.formation]];if(e.kind==='RIVALRY')return e.choices[0];if(e.kind==='PLAN')return e.choices[(g.period+style)%3];if(e.kind==='RECOVERY')return pick(g,`recovery:${recovery}`);if(e.kind==='DECISIVE')return e.choices[style%2];if(['INTEREST','CONTACT','OFFER','ASSESSMENT_RESULT'].includes(e.kind))return market==='move'?e.choices[0]:pick(g,'market:stay');return e.choices[0];
}
function complete(g,config={}){let n=0;while(g.phase!=='DONE'){assert.ok(validGame(g),`invalid ${g.event.kind}`);const c=policy(g,config);assert.ok(c,`${g.event.kind} choice`);assert.ok(choose(g,c.id));assert.ok(++n<=26);}assert.ok(validGame(g));return g;}
function sum(matches){return matches.reduce((s,m)=>{if(m.minutes){s.apps++;s.starts+=m.started?1:0;s.minutes+=m.minutes;s.goals+=m.goals;s.assists+=m.assists;s.ratingSum+=m.rating;}return s;},{apps:0,starts:0,minutes:0,goals:0,assists:0,ratingSum:0});}
let groups=0;const check=(name,fn)=>{fn();groups++;console.log('PASS',name);};
const outcomes=[];
check('100 careers /all8positions finish54 actual fixtures with exact stats and eighteen-round calendar',()=>{
 assert.equal(CLUBS.length,10);assert.equal(POSITIONS.length,8);
 for(let seed=1;seed<=100;seed++){const g=complete(createGame('Amostra',POSITIONS[(seed-1)%8].id,seed),{market:seed%3?'stay':'move',style:seed%3});outcomes.push(g);assert.equal(g.age,21);assert.equal(g.playedMatches.length,54);assert.equal(g.yearStats.length,3);assert.deepEqual(g.totalstats,sum(g.playedMatches));assert.ok(g.decisions<=25);assert.equal(g.choicesLog.length,g.decisions);assert.ok(g.choicesLog.every(c=>c.label&&c.id&&c.eventId));
 for(const s of g.yearStats){const matches=g.playedMatches.filter(m=>m.season===s.season),counts={};assert.equal(matches.length,18);for(const m of matches)counts[m.opponentId]=(counts[m.opponentId]??0)+1;assert.equal(Object.keys(counts).length,9);assert.ok(Object.values(counts).every(v=>v===2));assert.deepEqual(Object.fromEntries(Object.keys(g.totalstats).map(k=>[k,s[k]])),sum(matches));}
 for(let i=1;i<g.playedMatches.length;i++)assert.notEqual(g.playedMatches[i].opponentId,g.playedMatches[i-1].opponentId);
 assert.ok(g.playedMatches.every(m=>m.gf<=m.teamChances&&m.ga<=m.oppChances&&m.goals+m.assists<=m.gf&&m.completedPasses<=m.passAttempts&&m.assists<=m.keyPasses&&m.keyPasses<=m.completedPasses));assert.equal(g.progression.filter(p=>p.period>0).length,9);
 }
 console.log(JSON.stringify({sample100:{fixtures:5400,decisions:[Math.min(...outcomes.map(g=>g.decisions)),Math.max(...outcomes.map(g=>g.decisions))],overall21:[Math.min(...outcomes.map(overall)),Math.max(...outcomes.map(overall))],met:outcomes.reduce((s,g)=>s+g.objectiveHistory.filter(o=>o.status==='MET').length,0),missed:outcomes.reduce((s,g)=>s+g.objectiveHistory.filter(o=>o.status==='MISSED').length,0)}}));
});
check('two synthetic medium-quality origins and alternative intents do not force medium-quality confidence/trust collapse',()=>{
 const rows=[];
 for(const [position,seed,formation]of [['AM',120,[0,2,1]],['ST',103,[0,1,2]]])for(const style of [0,1,2]){
  const g=createGame('Origem',position,seed);while(g.event.kind==='FORMATION')choose(g,policy(g,{formation}).id);const initial=overall(g);choose(g,g.event.choices[position==='ST'?0:1].id);complete(g,{style,market:'stay',formation});assert.ok(initial>=40&&initial<=50);assert.ok(overall(g)>=initial+6);assert.ok(g.confidence>35);assert.ok(g.trust>20);assert.ok(g.pressure<65);assert.ok(g.totalstats.starts>0);assert.ok(g.recoveryArc);assert.ok(g.playedMatches.some(m=>m.good));rows.push({position,seed,style,initial,final:overall(g),starts:g.yearStats.map(s=>s.starts),apps:g.totalstats.apps,goals:g.totalstats.goals,assists:g.totalstats.assists,confidence:+g.confidence.toFixed(1),trust:+g.trust.toFixed(1),pressure:+g.pressure.toFixed(1),met:g.objectiveHistory.filter(o=>o.status==='MET').length});
 }
 console.log(JSON.stringify({syntheticOrigins:rows}));
});
check('goals not required every AM game; short appearances and bench give only real partial evidence',()=>{
 const g=outcomes.find(g=>g.position==='AM');assert.ok(g.playedMatches.some(m=>m.goals===0&&m.assists===0&&m.chancesCreated>0&&m.rating>=7));
 for(const game of outcomes)for(const m of game.playedMatches){if(!m.minutes){assert.equal(m.rating,0);for(const k of ['goals','assists','shots','completedPasses','chancesCreated','interventions','saves'])assert.equal(m[k],0);assert.match(m.coach,/Sem minutos/);}if(m.minutes>0&&m.minutes<35){assert.match(m.coach,/Evidência parcial/);assert.equal(m.good,false);assert.ok(m.rating>=6.2);}}
 const keeper=outcomes.find(g=>g.position==='GK');assert.ok(keeper.playedMatches.every(m=>m.goals===0));assert.ok(keeper.playedMatches.some(m=>m.saves>0));
});
check('objectives meet and miss actual criteria and recovery work changes future learning rather than granting a place',()=>{
 let recovery=null;for(const g of outcomes){for(const o of g.objectiveHistory){assert.ok(o.season>=18&&o.season<=20);assert.ok(o.period>=1&&o.period<=3);assert.ok(g.playedMatches.some(m=>m.season===o.season&&m.clubId===o.clubId));const met=Object.keys(o.target).every(k=>o.progress[k]>=o.target[k]);assert.equal(o.status,met?'MET':'MISSED');assert.ok(o.target.good>=2);assert.ok(o.target.output>0);}if(!recovery&&g.recoveryArc)recovery=g;}
 assert.ok(outcomes.some(g=>g.objectiveHistory.some(o=>o.status==='MET')));assert.ok(outcomes.some(g=>g.objectiveHistory.some(o=>o.status==='MISSED')));
 const base=createGame('Resposta',recovery.position,recovery.seed);while(base.event.kind!=='RECOVERY')choose(base,policy(base).id);const previous=JSON.stringify(base.playedMatches),extra=structuredClone(base),read=structuredClone(base),trust=base.trust;choose(extra,pick(extra,'recovery:EXTRA').id);choose(read,pick(read,'recovery:READ').id);assert.equal(extra.trust,trust);assert.equal(read.trust,trust);assert.equal(JSON.stringify(extra.playedMatches),previous);choose(extra,extra.event.choices[0].id);choose(read,read.event.choices[0].id);assert.notDeepEqual(extra.progression.at(-1).skillChanges,read.progression.at(-1).skillChanges);assert.ok(extra.condition<read.condition);assert.ok(extra.fatigue>read.fatigue);assert.ok(extra.fanMemory[extra.clubId].criticalEntries.some(s=>s.includes('Resposta EXTRA')));
});
check('opportunity-safe decisive posture never treats a cameo as a heroic proof; choices vary with project/period',()=>{
 const g=createGame('Postura','ST',103);while(g.event.kind!=='DECISIVE')choose(g,policy(g).id);const past=JSON.stringify(g.playedMatches),risk=structuredClone(g),safe=structuredClone(g);choose(risk,risk.event.choices[0].id);choose(safe,safe.event.choices[1].id);assert.equal(JSON.stringify(risk.playedMatches),past);assert.equal(JSON.stringify(safe.playedMatches),past);choose(risk,risk.event.choices[0].id);choose(safe,safe.event.choices[0].id);assert.ok(risk.lastMatches.filter(m=>m.moment).every(m=>m.minutes>=45));assert.ok(safe.lastMatches.filter(m=>m.moment).every(m=>m.minutes>=45));assert.notDeepEqual(risk.lastMatches,safe.lastMatches);
 const menus=g.choicesLog.filter(c=>c.kind==='PLAN').map(c=>c.label);assert.ok(new Set(menus).size>=3);
});
check('market needs role evidence; bigger project has rival/minute cost, fallback assessment may fail',()=>{
 let offerSeed=null,assessment=null;for(const g of outcomes){if(g.history.length>1&&!offerSeed)offerSeed=g.seed;if(g.choicesLog.some(c=>c.kind==='ASSESSMENT_RESULT'))assessment=g;}
 assert.ok(offerSeed);const g=createGame('Mercado',POSITIONS[(offerSeed-1)%8].id,offerSeed);let found=false;while(g.phase!=='DONE'){if(g.event.kind==='INTEREST'){assert.ok(g.market.length<=3);for(const id of g.market)assert.ok(CLUBS.some(c=>c.id===id));if(g.market.length>=2)found=true;}const oldKind=g.event.kind;choose(g,policy(g,{market:'move'}).id);if(oldKind==='OFFER'){assert.deepEqual(g.lastMatches,[]);assert.equal(g.roleEvidence,null);assert.equal(g.coachReaction,'');assert.equal(g.fanReaction,'');assert.ok(g.lastOutcome.season<g.season);}}assert.ok(g.history.length>1);assert.ok(g.choicesLog.some(c=>c.kind==='CONTACT'));assert.ok(g.choicesLog.some(c=>c.kind==='OFFER'));
 const low=createGame('Baixo','ST',9);while(low.event.kind!=='PLAN')choose(low,policy(low).id);for(const k of Object.keys(low.skills))low.skills[k]=30;low.proficiency=35;complete(low,{market:'move'});assert.ok(low.history.length<=2);assert.ok(low.objectiveHistory.some(o=>o.status==='MISSED'));assert.ok(low.totalstats.starts<g.totalstats.starts);assert.ok(low.event.body.includes('recorte'));
 for(let seed=100;seed<160&&!assessment;seed++){const q=createGame('Avaliação','ST',seed);while(q.event.kind!=='PLAN')choose(q,policy(q).id);for(const k of Object.keys(q.skills))q.skills[k]=32;q.proficiency=40;complete(q,{market:'move',style:2});if(q.choicesLog.some(c=>c.kind==='ASSESSMENT_RESULT'))assessment=q;}assert.ok(assessment,'observed failed assessment, no automatic contract');
 console.log(JSON.stringify({marketSample:{offerSeed,distinctProjects:found,low:{overall:overall(low),starts:low.totalstats.starts,clubs:low.history.map(h=>h.clubId)},assessmentFailureSeen:!!assessment}}));
});
check('exact replay and full JSON continuation; deterministic learned formation; finite hydration rejects schema1/NaN',()=>{
 const g=createGame('Replay','CB',7),before=JSON.stringify(g),id=g.event.choices[0].id;assert.equal(choose(g,'forged'),false);assert.equal(JSON.stringify(g),before);choose(g,id);const after=JSON.stringify(g);assert.equal(choose(g,id),false);assert.equal(JSON.stringify(g),after);const loaded=JSON.parse(after);complete(g);complete(loaded);assert.deepEqual(g,loaded);const done=JSON.stringify(g);assert.equal(choose(g,id),false);assert.equal(JSON.stringify(g),done);
 const a=createGame('Treino','CM',88),b=structuredClone(a);b.rng=123;for(let i=0;i<3;i++){choose(a,a.event.choices[0].id);choose(b,b.event.choices[0].id);}assert.deepEqual(a.skills,b.skills);assert.equal(a.age,18);assert.equal(a.objective.status,'MET');assert.equal(a.objective.progress.stages,3);assert.equal(a.objective.progressText,'3/3 etapas concluídas');
 for(const mutate of [q=>q.schema=1,q=>q.skills.passing=NaN,q=>q.condition=101,q=>q.event.choices=[{id:'intent:BAD@'+q.serial,label:'BAD',hint:'BAD'}],q=>q.position='NO',q=>q.dna.learning=Infinity,q=>q.totalstats.apps++,q=>q.event.id='wrong-serial']){const q=createGame('Guard','CM',4);mutate(q);assert.equal(validGame(q),false);}const badHistory=structuredClone(outcomes[0]);badHistory.objectiveHistory[0].clubId='unknown';assert.equal(validGame(badHistory),false);const badPeriod=structuredClone(outcomes[0]);badPeriod.objectiveHistory[0].period=4;assert.equal(validGame(badPeriod),false);const sample=outcomes[0],raw=JSON.stringify(sample);assert.ok(validGame(sample));assert.equal(JSON.stringify(sample),raw);assert.ok(validGame(JSON.parse(raw)));const replay=createGame(sample.name,sample.position,sample.seed);for(const c of sample.choicesLog)assert.ok(choose(replay,c.id));assert.deepEqual(replay,sample);
});
check('review P2 hydration regressions reject before mutation or exception; objective evidence cannot be forged',()=>{
 const clinical=createGame('Passe real','GK',2654435761);while(clinical.event.kind==='FORMATION')choose(clinical,clinical.event.choices[clinical.formation].id);choose(clinical,clinical.event.choices[1].id);while(clinical.phase!=='DONE'){const choice=clinical.event.kind==='PLAN'?pick(clinical,'intent:SAFE'):clinical.event.kind==='DECISIVE'?clinical.event.choices[1]:policy(clinical,{recovery:'COOPERATE'});assert.ok(choose(clinical,choice.id));}for(const m of clinical.playedMatches){assert.ok(m.assists<=m.keyPasses);assert.ok(m.keyPasses<=m.completedPasses);}
 const plan=createGame('Hydration','AM',13);while(plan.event.kind!=='PLAN')choose(plan,plan.event.choices[0].id);
 const malformed=[q=>q.rival=null,q=>q.fanMemory[q.clubId].respect='broken',q=>q.objective.clubId='gremio',q=>Object.keys(q.objective.target).forEach(k=>q.objective.target[k]=0),q=>q.roleEvidence={minutes:'broken'},q=>{q.event.kind='RECOVERY';q.event.choices=[{id:`recovery:EXTRA@${q.serial}`,label:'extra',hint:'extra'}];q.recoveryArc=null;q.recoveryUsed=true;},q=>q.objective.progress.good=2,q=>q.objective.target.minutes=1,q=>q.objective.period=2,q=>q.objective.season=19];
 for(const mutate of malformed){const q=structuredClone(plan);mutate(q);const before=JSON.stringify(q);assert.equal(validGame(q),false);assert.doesNotThrow(()=>assert.equal(choose(q,q.event.choices[0].id),false));assert.equal(JSON.stringify(q),before);}
 const genuine=structuredClone(plan);assert.ok(choose(genuine,genuine.event.choices[0].id));assert.ok(validGame(JSON.parse(JSON.stringify(genuine))));const forged=structuredClone(genuine);forged.objectiveHistory[0].progress.good++;assert.equal(validGame(forged),false);const before=JSON.stringify(forged);assert.equal(choose(forged,forged.event.choices[0].id),false);assert.equal(JSON.stringify(forged),before);
});
check('null UI history items and impossible action counters reject without mutation; eight roles hydrate',()=>{
 const base=createGame('Arrays','AM',13);while(base.event.kind!=='PLAN')choose(base,base.event.choices[0].id);choose(base,base.event.choices[0].id);
 for(const mutate of [q=>q.progression=[null],q=>q.history=[null],q=>q.log=[null],q=>q.lastMatches=[null],q=>q.playedMatches[0].shots=-1,q=>q.playedMatches[0].shotsOnTarget=123,q=>q.playedMatches[0].interventions=.5,q=>q.progression[0].skillChanges=null,q=>q.lastOutcome={title:null,body:'bad'}]){const q=structuredClone(base);mutate(q);const before=JSON.stringify(q);assert.equal(validGame(q),false);assert.equal(choose(q,q.event.choices[0].id),false);assert.equal(JSON.stringify(q),before);}
 for(const p of POSITIONS){const g=createGame('Roundtrip',p.id,120);while(g.phase!=='DONE'){const loaded=JSON.parse(JSON.stringify(g));assert.ok(validGame(loaded));assert.deepEqual(loaded,g);assert.ok(choose(g,policy(g,{market:'move'}).id));}assert.ok(validGame(JSON.parse(JSON.stringify(g))));}
});
console.log(`prototype02-engine: ${groups} groups passed`);
