import { competitionCategory, CATEGORY_LABEL } from './core/calendar.js';
import { coachDossier, coachBond, coachName, bondLabel, ensureCoaching, standings, coachProfile } from './core/coaches.js';
import { REAL_COACHES } from './data/coaches.js';
import { createCareer, advanceCareer, resolveChoice, overallVisible, getClub, clubCount, getPositionLabel, setTransferIntent, transferIntentLabel } from './core/engine.js';
import { loadSave, storeSave, clearSave, exportDiagnostic } from './core/persistence.js';
import { BRAZIL_CLUBS_2026 } from './data/clubs-br-2026.js';
import { POSITIONS, POSITION_LABEL, coachPositionFeedback } from './core/positions.js';
import type { SaveGame, TransferIntent, VisibleAttributes, CareerEvent, SeasonStats } from './core/types.js';

let save:SaveGame|null=loadSave();
let tab='career';
const root=document.querySelector<HTMLDivElement>('#app')!;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]!));
const pct=(v:number)=>v>=82?'Muito alta':v>=66?'Alta':v>=45?'Média':v>=28?'Baixa':'Muito baixa';
const money=(v:number)=>v<=0?'—':v<1_000_000?`R$ ${(v/1000).toFixed(0)} mil`:`R$ ${(v/1_000_000).toFixed(v>=100_000_000?0:1)} mi`;
const posLabel=(p:string)=>p==='IND'?'Indefinida':POSITION_LABEL[p as keyof typeof POSITION_LABEL]??p;

function theme(){
  const c=save?getClub(save.player.currentClubId):null;const colors=c?.colors??['#7bbcff','#e8eef4'];
  return `style="--club:${colors[0]};--club2:${colors[1]};"`;
}
function appShell(content:string){return `<main class="shell" ${theme()}><div class="brand"><div><h1>1903</h1><span class="subbrand">CARREIRA</span></div><span class="build">0.3 · EXPERIMENTAL</span></div>${content}${save?nav():''}</main>`;}
function nav(){return `<div class="bottom-nav"><div class="bottom-nav-inner">${[['career','Carreira'],['player','Jogador'],['stats','Estatísticas'],['world','Mundo']].map(([id,l])=>`<button class="nav ${tab===id?'active':''}" data-tab="${id}">${l}</button>`).join('')}</div></div>`;}
function clubOptions(){return BRAZIL_CLUBS_2026.slice().sort((a,b)=>a.division.localeCompare(b.division)||a.name.localeCompare(b.name,'pt-BR')).map(c=>`<option value="${c.id}" ${c.id==='gremio'?'selected':''}>${esc(c.name)} · Série ${c.division}</option>`).join('');}
function renderCreate(){root.innerHTML=appShell(`<section class="cover"><span class="eyebrow">12 ANOS · 2026</span><h2>Uma vida diferente.<br>Decisões suas.</h2><p>Cidade, família, infância e características são sorteadas. Você começa numa escolinha local e conduz as escolhas que podem mudar sua carreira.</p></section><div class="form"><label>Nome do jogador</label><input id="name" value="Luciano Basso" maxlength="32"><button class="action primary" id="new">COMEÇAR A CARREIRA</button></div><div class="footnote">Save local neste aparelho · sem conta · sem servidor</div>`);bind();}

function feedbackCard(e:CareerEvent):string{
  const f=e.matchFeedback;if(!f)return '';
  return `<section class="performance-card" aria-label="Quadro da atuação"><div class="performance-heading"><span class="eyebrow">${f.blockGames?'ATUAÇÃO NA PARTIDA':'SEM PARTICIPAÇÃO'}</span><strong>${f.rating?f.rating.toFixed(1):'—'}<small>NOTA</small></strong></div><div class="match-category">${esc(f.category?CATEGORY_LABEL[f.category]:'Categoria não registrada')}</div><h4>${f.blockGames||f.showScore?`${f.teamGoals} × ${f.oppGoals} · ${esc(f.opponent)}`:esc(f.opponent)}</h4><div class="performance-metrics"><div><b>${f.minutes}</b><span>MINUTOS</span></div><div><b>${f.goals}</b><span>GOLS</span></div><div><b>${f.assists}</b><span>ASSIST.</span></div>${save!.player.position==='GK'?`<div><b>${f.saves}</b><span>DEFESAS</span></div>`:''}</div><div class="minutes-track" aria-label="${f.minutes} minutos em 90"><i style="width:${f.minutes/90*100}%"></i></div><small>${f.blockGames?(f.started?'Começou como titular':'Entrou durante a partida'):'Não entrou em campo'}</small><div class="performance-reactions"><div><span>TORCIDA</span><p>${esc(f.fanReaction)}</p></div><div><span>${esc(f.coachName).toUpperCase()}</span><p>${esc(f.coachReaction)}</p></div></div><div class="performance-block">Uma partida neste turno · ${f.minutes} minutos em campo</div></section>`;
}
function seasonPosition(s:SeasonStats):string{
 const positions=s.positionsPlayed??[];const primary=s.primaryPosition??(positions.length===1?positions[0]:undefined);
 if(!primary)return 'Posição não registrada';
 return `${posLabel(primary)}${positions.length>1?' · também '+positions.filter(x=>x!==primary).map(x=>posLabel(x)).join(', '):''}`;
}
function seasonCategoryRows(s:SeasonStats):string{
 if(!s.categories)return '<small>Categoria não registrada neste save antigo</small>';
 return `<div class="category-stats">${Object.entries(s.categories).map(([key,c])=>`<div><b>${esc(CATEGORY_LABEL[key as keyof typeof CATEGORY_LABEL])}</b><span>${c!.appearances}J · ${c!.minutes} min · ${c!.goals}G · ${c!.assists}A</span></div>`).join('')}</div>`;
}
function currentCoachCard():string{
 const p=save!.player;if(!p.currentClubId||p.age<16)return '';
 const job=ensureCoaching(p).jobs[p.currentClubId];if(!job)return '';
 const bond=coachBond(p,job.coachId);
 return `<article class="coach-card"><span class="eyebrow">COMANDO TÉCNICO</span><h3>${esc(coachName(job.coachId))}</h3><p>${esc(coachDossier(p,p.currentClubId))}</p><div class="tags"><span>${esc(bondLabel(bond))}</span><span>Confiança profissional ${bond.trust>=65?'alta':bond.trust<40?'baixa':'em construção'}</span></div>${bond.memories.length?`<small>${esc(bond.memories[0]!)}</small>`:''}</article>`;
}
function coachDatabase():string{
 return `<details class="coach-database"><summary>Banco de treinadores · ${REAL_COACHES.length} nomes reais</summary><p>Nomes reais; projetos, perfis e relações desta carreira são simulados.</p><input id="coach-search" type="search" placeholder="Buscar treinador" aria-label="Buscar treinador"><div id="coach-results">${coachRows('')}</div></details>`;
}
function coachRows(query:string):string{
 const normal=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const matches=REAL_COACHES.filter(c=>normal(c.name).includes(normal(query)));
 return matches.map(c=>{const profile=coachProfile(c.id);return `<div class="coach-db-row"><b>${esc(c.name)}</b><small>${c.market==='REGIONAL'?'Referência no futebol regional':c.market==='BRAZIL'?'Referência no mercado brasileiro':'Referência internacional'}${c.historicalOnly?' · acervo histórico':''}</small><span>Perfil de jogo: ${profile.style==='POSSESSION'?'posse':profile.style==='DIRECT'?'verticalidade':'organização defensiva'} · ${profile.dialogue>=60?'mais aberto ao diálogo':'mais firme na negociação'}</span></div>`;}).join('')||'<div class="empty">Nenhum treinador encontrado.</div>';
}
function eventCard(){if(!save?.pendingEvent)return save?.player.phase==='APOSENTADO'?`<div class="empty">Carreira encerrada. ${save.player.life?.secondCareer?.path==='TECHNICAL'?'Novo caminho: formação técnica.':save.player.life?.secondCareer?.path==='DEGREE'?'Novo caminho: formação superior.':save.player.life?.secondCareer?.path==='COACH_COURSE'?'Novo caminho: formação para treinador.':'Novo caminho: buscar uma ocupação.'} Seu histórico permanece disponível.</div>`:'<button class="action primary" id="advance">CONTINUAR</button>';const e=save.pendingEvent;return `<article class="event-card"><div class="event-top"><span class="eyebrow">${({INFO:'CARREIRA',CHOICE:'DECISÃO',MATCH:'PARTIDA',SEASON_END:'TEMPORADA',MARKET:'MERCADO',MILESTONE:'MARCO'}[e.kind])}</span><span class="event-age">${save.player.age} anos</span></div><h3>${esc(e.title)}</h3><p>${esc(e.body)}</p>${feedbackCard(e)}<div class="tags">${e.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>${e.choices?.map(c=>`<button class="choice" data-choice="${c.id}"><b>${esc(c.label)}</b>${c.hint?`<small>${esc(c.hint)}</small>`:''}</button>`).join('')??`<button class="action primary" id="advance">CONTINUAR</button>`}</article>`;}
function seasonStrip(){const p=save!.player,s=p.currentSeason.categories?.[competitionCategory(p)]??p.currentSeason;return `<div class="season-category">${esc(CATEGORY_LABEL[competitionCategory(p)])} · nesta temporada</div><div class="season-strip"><div><b>${s.appearances}</b><span>J</span></div><div><b>${s.goals}</b><span>G</span></div><div><b>${s.assists}</b><span>A</span></div><div><b>${s.motm??0}</b><span>MOTM</span></div><div><b>${s.avgRating?s.avgRating.toFixed(1):'—'}</b><span>NOTA</span></div></div>`;}
function renderCareer(){const p=save!.player,c=getClub(p.currentClubId);root.innerHTML=appShell(`<header class="player-head"><div><span class="eyebrow">${p.season} · ${CATEGORY_LABEL[competitionCategory(p)]}</span><h2>${esc(p.name)}</h2><p>${c?`${esc(c.name)} · ${esc(c.city)}`:esc(p.life?.localSchool??'Escolinha local')} · ${p.age} anos · ${p.heightCm.toFixed(0)} cm</p></div><div class="ovr"><b>${overallVisible(p)}</b><span>OVR</span></div></header>${seasonStrip()}<div class="state-row"><div><span>Moral</span><b>${pct(p.morale)}</b></div><div><span>Confiança</span><b>${pct(p.confidence)}</b></div><div><span>Posição</span><b>${esc(getPositionLabel(p))}</b></div></div>${eventCard()}<div class="section-title">Memória recente</div><div class="timeline">${p.history.slice(0,8).map(h=>`<div class="timeline-item"><i></i><div><b>${esc(h.headline)}</b><span>${h.season} · ${h.age} anos — ${esc(h.detail)}</span></div></div>`).join('')||'<div class="empty">A carreira está apenas começando.</div>'}</div>`);bind();}

function attrRow(k:keyof VisibleAttributes,label:string){const p=save!.player,know=p.attributeKnowledge[k],v=p.attributes[k];const shown=know<18?'?':know<58?`${Math.max(20,Math.round(v-6))}–${Math.min(99,Math.round(v+6))}`:Math.round(v).toString();const cls=know<18?'unknown':'';return `<div class="attribute ${cls}"><span>${label}</span><b>${shown}</b></div>`;}
function positionGrid(){const p=save!.player;return `<div class="position-grid">${POSITIONS.map(pos=>`<div class="position-cell ${p.position===pos?'current':''}"><span>${POSITION_LABEL[pos]}</span><b>${Math.round(p.positionProficiency[pos])}</b><small>experiência</small></div>`).join('')}</div>`;}
function renderPlayer(){const p=save!.player,c=getClub(p.currentClubId);const foot=p.age<=12?'em descoberta':p.dna.dominantFoot==='D'?'direito':'esquerdo';root.innerHTML=appShell(`<header class="player-head compact"><div><span class="eyebrow">PERFIL</span><h2>${esc(p.name)}</h2><p>${esc(getPositionLabel(p))} · pé ${foot} · ${p.heightCm.toFixed(1)} cm · ${p.weightKg.toFixed(1)} kg</p></div><div class="ovr"><b>${overallVisible(p)}</b><span>OVR</span></div></header><div class="quote">“${esc(coachPositionFeedback(p))}”<span>leitura atual do treinador</span></div><div class="section-title">Experiência por posição</div>${positionGrid()}<div class="detail-card"><div><span>Origem</span><b>${esc(p.hometown)}</b></div><div><span>Família</span><b>${esc(p.life?.family.parents.join(' e ')??'Em descoberta')}</b></div><div><span>Estudos</span><b>${p.life?.education.completed?'Escola concluída':p.age<=18?'Em formação':'Escola incompleta'}</b></div><div><span>Função</span><b>${p.tactical?.role==='HOLD'?'Mais fixa':p.tactical?.role==='MOBILE'?'Mais móvel':'Equilibrada'}</b></div></div><div class="section-title">Características descobertas</div><div class="attr-grid">${attrRow('technique','Técnica')}${attrRow('passing','Passe')}${attrRow('finishing','Finalização')}${attrRow('dribbling','Drible')}${attrRow('vision','Visão')}${attrRow('decisions','Decisão')}${attrRow('pace','Velocidade')}${attrRow('stamina','Resistência')}${attrRow('strength','Força')}${attrRow('positioning','Posicionamento')}${attrRow('tackling','Desarme')}${attrRow('crossing','Cruzamento')}${attrRow('heading','Cabeceio')}${attrRow('reflexes','Reflexos')}${attrRow('handling','Mãos')}${attrRow('aerial','Jogo aéreo')}</div><div class="detail-card"><div><span>Clube</span><b>${c?.name??'Escolinha'}</b></div><div><span>Clube do coração</span><b>${getClub(p.heartClubId)?.name??'—'}</b></div><div><span>Valor</span><b>${money(p.marketValue)}</b></div><div><span>Contrato</span><b>${p.contractYearsLeft?p.contractYearsLeft+' ano'+(p.contractYearsLeft>1?'s':''):'—'}</b></div></div>`);bind();}

function barChart(rows:{label:string,value:number,display:string}[]){const max=Math.max(1,...rows.map(r=>r.value));return `<div class="bars">${rows.map(r=>`<div class="bar-row"><span>${esc(r.label)}</span><div class="bar-track"><i style="width:${Math.max(2,r.value/max*100).toFixed(1)}%"></i></div><b>${esc(r.display)}</b></div>`).join('')}</div>`;}
function renderStats(){const p=save!.player,s=p.careerStats;const seasons=p.seasonHistory.slice(0,8).reverse();const chart=barChart(seasons.map(x=>({label:String(x.season).slice(-2),value:x.categories?.SENIOR?(x.categories.SENIOR.goals+x.categories.SENIOR.assists):0,display:String(x.categories?.SENIOR?(x.categories.SENIOR.goals+x.categories.SENIOR.assists):0)})));root.innerHTML=appShell(`<section class="stat-hero"><span class="eyebrow">CARREIRA PROFISSIONAL · BASE CONTADA À PARTE</span><div class="career-total">${s.goals}<small>gols</small></div><p>${s.appearances} jogos · ${s.assists} assistências · ${s.motm}× melhor em campo</p></section><div class="grid six"><div class="metric"><b>${s.goals}</b><span>GOLS</span></div><div class="metric"><b>${s.assists}</b><span>ASSIST.</span></div><div class="metric"><b>${s.motm}</b><span>MOTM</span></div><div class="metric"><b>${s.reds}</b><span>VERM.</span></div><div class="metric"><b>${s.titles.length}</b><span>TÍTULOS</span></div><div class="metric"><b>${s.cleanSheets}</b><span>CS</span></div></div><div class="section-title">Produção profissional G+A por temporada</div><div class="chart-card">${seasons.length?chart:'<div class="empty">Ainda não há temporadas profissionais concluídas.</div>'}</div><div class="section-title">Temporadas</div>${p.seasonHistory.map(x=>`<article class="season-card"><div><span>${x.season}</span><b>${x.age} anos</b></div><h3>${getClub(x.clubId)?.shortName??'Formação'}</h3><div class="season-position">${esc(seasonPosition(x))}</div>${seasonCategoryRows(x)}<p>Total da temporada: ${x.appearances}J · ${x.goals}G · ${x.assists}A · ${x.motm} MOTM${x.avgRating?` · ${x.avgRating.toFixed(2)}`:''}${x.titles.length?` · 🏆 ${x.titles.join(', ')}`:''}</p><small>${money(x.marketValueStart)} → ${money(x.marketValueEnd)}</small></article>`).join('')||'<div class="empty">A primeira temporada ainda está em andamento.</div>'}`);bind();}

function relationLabel(r:{passion:number;hate:number;fear:number;respect:number}){const vals:[string,number][]=[['Paixão',r.passion],['Ódio',r.hate],['Temor',r.fear],['Respeito',r.respect]];return vals.sort((a,b)=>b[1]-a[1])[0]!;}
function intentButtons(){const p=save!.player;const intents:TransferIntent[]=['STAY','OPEN','LEAVE','FORCE'];return `<div class="intent-grid">${intents.map(i=>`<button class="intent ${p.transferIntent===i?'active':''}" data-intent="${i}">${transferIntentLabel(i)}</button>`).join('')}</div>`;}
function renderWorld(){const p=save!.player;const rel=Object.values(p.fanRelations).filter(x=>Math.max(x.passion,x.hate,x.fear,x.respect)>1).sort((a,b)=>Math.max(b.passion,b.hate,b.fear,b.respect)-Math.max(a.passion,a.hate,a.fear,a.respect)).slice(0,8);root.innerHTML=appShell(`<section class="world-head"><span class="eyebrow">MUNDO</span><h2>Brasil · 156 clubes</h2><p>Seu nome começa a significar coisas diferentes em cada estádio.</p></section>${currentCoachCard()}${save!.player.currentClubId&&p.coaching?`<div class="section-title">Campanha do clube</div><div class="league-table">${standings(p,p.currentClubId!).map((c,i)=>`<div class="league-row ${c.clubId===p.currentClubId?'current':''}"><span>${i+1}</span><b>${esc(getClub(c.clubId)!.shortName)}</b><span>${c.games}J</span><strong>${c.points} pts</strong></div>`).join('')}</div>`:''}<div class="section-title">Minha posição no mercado</div>${intentButtons()}<div class="section-title">Torcidas</div><div class="relation-list">${rel.length?rel.map(r=>{const [label,v]=relationLabel(r);return `<div class="relation"><div><b>${getClub(r.clubId)?.name??r.clubId}</b><span>${label}</span></div><strong>${Math.round(v)}</strong></div>`}).join(''):'<div class="empty">Ainda é cedo para o futebol ter uma opinião forte sobre você.</div>'}</div><div class="section-title">Transferências</div>${p.transferHistory.length?p.transferHistory.map(t=>`<div class="transfer"><span>${t.season}</span><b>${getClub(t.fromClubId)?.shortName??'Formação'} → ${getClub(t.toClubId)?.shortName}</b><strong>${money(t.fee)}</strong></div>`).join(''):'<div class="empty small">Nenhuma transferência profissional.</div>'}${coachDatabase()}<div class="section-title">Desenvolvimento</div><button class="action" id="export">Exportar diagnóstico completo</button><button class="action danger" id="reset">Apagar carreira</button>`);bind();}

function render(){if(!save)return renderCreate();if(tab==='player')return renderPlayer();if(tab==='stats')return renderStats();if(tab==='world')return renderWorld();renderCareer();}
function bind(){
  document.querySelector<HTMLInputElement>('#coach-search')?.addEventListener('input',e=>{document.querySelector('#coach-results')!.innerHTML=coachRows((e.target as HTMLInputElement).value);});
  document.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab!;render();});
  document.querySelector('#new')?.addEventListener('click',()=>{const n=(document.querySelector<HTMLInputElement>('#name')!.value||'Jogador').trim();save=createCareer(n);storeSave(save);render();});
  document.querySelector('#advance')?.addEventListener('click',()=>{if(!save)return;save=advanceCareer(save);storeSave(save);render();});
  document.querySelectorAll<HTMLElement>('[data-choice]').forEach(b=>b.onclick=()=>{if(!save)return;save=resolveChoice(save,b.dataset.choice!);storeSave(save);save=advanceCareer(save);storeSave(save);render();});
  document.querySelectorAll<HTMLElement>('[data-intent]').forEach(b=>b.onclick=()=>{if(!save)return;save=setTransferIntent(save,b.dataset.intent as TransferIntent);storeSave(save);render();});
  document.querySelector('#export')?.addEventListener('click',()=>save&&exportDiagnostic(save));
  document.querySelector('#reset')?.addEventListener('click',()=>{if(confirm('Apagar esta carreira e começar de novo?')){clearSave();save=null;tab='career';render();}});
}
render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
